### ISSUE TITLE
贴吧开屏广告似乎还是会弹出来

### ISSUE THREAD

**Issue by codexss** [app2smile/rules#1]
可能需要加上这两条规则
DOMAIN,mi.gdt.qq.com,REJECT
DOMAIN,api-access.pangolin-sdk-toutiao.com,REJECT
![C73F408F-3DCC-4928-A413-6D135C2FB49F](https://user-images.githubusercontent.com/5959201/131211941-ee8fc706-3700-4107-8d5b-52feb2ff6129.png)

**Comment by app2smile** [comment]
未能复现,有无复现步骤?

**Comment by codexss** [comment]
开启贴吧后app直接访问了上述两个sdk的域名
然后才访问的afd.baidu.com
![086020D0-5E6C-4055-9DF8-84813A537E96](https://user-images.githubusercontent.com/5959201/131214686-16512eb1-3e99-4304-8ed6-dbe301c2b379.png)

**Comment by codexss** [comment]
可能是广告缓存还在目录里，多开了几遍app没有加载这两个域名的请求了，先关闭了 晚点如果复现再开…

**Comment by app2smile** [comment]
> 可能是广告缓存还在目录里，多开了几遍app没有加载这两个域名的请求了，先关闭了 晚点如果复现再开…

与缓存和你说的那两个无关。
经排查，目前ios15beta7，最新surge tf版本下，使用贴吧时，关闭wifi切换到蜂窝5g，去广告失效（很大可能是在切的过程中没有拦截贴吧的网络请求导致贴吧再次查询dns，以至于加载了广告和获取到了ip地址来请求后续接口）

正常单独使用wifi或单独使用蜂窝，或蜂窝切wifi均不会有失效的情况。

因暂不明确具体原因，不修改逻辑。
