### ISSUE TITLE
贴吧推荐页广告

### ISSUE THREAD

**Issue by yfue** [app2smile/rules#10]
大佬推荐页又出现广告了，清除缓存等操作都搞不定，但只有这个地方有广告
![1D818AD1-2CCD-4651-937D-F4C1DF92D6F3](https://user-images.githubusercontent.com/58805062/138568395-90682236-d41d-4979-ae46-7fba1bb2afb1.png)

**Comment by app2smile** [comment]
这个广告目前还有没有

**Comment by yfue** [comment]
> 这个广告目前还有没有

后面搭配了https://github.com/yfue/surge/raw/Module/Adbock.list 就没有了，这段时间没看。猜测是广告联盟的广告，模块里面没有，但是一般都搭配了其他规则所以没有影响

**Comment by app2smile** [comment]
这个是优量汇的广告。贴吧有自己的一套广告逻辑，如果开启了程序化广告屏蔽，那么不会加载广告联盟的广告。

我这边测试不屏蔽其他广告联盟，通过脚本调整贴吧广告加载优先级，是有效的
