### ISSUE TITLE
新版粉色B站，draw类型(图文类型)动态只显示图片不显示文字

### ISSUE THREAD

**Issue by kokoryh** [app2smile/rules#103]
RT，脚本正常输出日志，无报错。仅粉色B站使用proto脚本会出现此问题，使用qx、surge测试均复现。白色B站无此问题

**Comment by kokoryh** [comment]
已提交pr

**Comment by app2smile** [comment]
最近一直忙 没管这个.  pr无法合并, 因为proto这块是写了个程序提取再转json的
