### ISSUE TITLE
贴吧12.37.5版本无法去广告

### ISSUE THREAD

**Issue by yidasanqian** [app2smile/rules#109]
希望尽快更新

**Comment by yidasanqian** [comment]
> 抓包 然后搜索一下sync接口，看看匹配到规则没有

匹配到去广告的脚本了，但是无法去广告

**Comment by app2smile** [comment]
先看sync接口,匹配的规则 ,然后再去看日志 .
可以把截图贴上来

**Comment by yidasanqian** [comment]
![457d50f2dcb2d1c6e646cf495a2fd80](https://user-images.githubusercontent.com/10655188/227074661-f082cf4c-8f87-4bdf-a49a-41289322b7f4.jpg)

**Comment by app2smile** [comment]
额. 看这个没用. 这个只能说明tiebajson脚本执行了
你先把贴吧后台杀掉, 然后打开抓包, 再打开贴吧. 等待几秒后再关闭抓包

在抓包的记录中 搜索sync接口, 看看匹配到了什么规则

**Comment by app2smile** [comment]
另外有两个日志  一个是json 主要用来去看图模式的广告和配置变更
一个是proto的 用来去贴吧大部分的广告

**Comment by yidasanqian** [comment]
proto这个脚本没执行，json这个执行了

**Comment by yidasanqian** [comment]
你那边更新到最新版贴吧应该也能重现吧

**Comment by app2smile** [comment]
无法重现 一般proto脚本没有日志 大概率是sync接口被其他的规则拦截导致的. 去广告必须要sync接口被本脚本正常修改,
你可以看看你的贴吧json日志 有没有sync的日志

**Comment by app2smile** [comment]
![image](https://user-images.githubusercontent.com/34903735/227084279-382f2016-7141-4f2b-b90a-86bed6a9baa0.png)

**Comment by yidasanqian** [comment]
那就很奇怪了，日志是正常输出的，下图是json脚本的执行
![image](https://user-images.githubusercontent.com/10655188/227087405-8f40c401-d2ff-42fa-9e33-dc6a009f3afe.png)

**Comment by yidasanqian** [comment]
还是有广告
![image](https://user-images.githubusercontent.com/10655188/227088272-3fb0eb05-1d27-416a-b75e-e44330366418.png)

**Comment by app2smile** [comment]
杀掉后台, 抓包, 然后打开贴吧 刷新推荐首页后, 接下来可以搜索180.76.76.200 这个请求,看是不是被拦截, 正常情况是应该被拦截.

然后再搜索personalized接口,看看有没有这个请求,有的话看看匹配情况 这个接口是首页推荐的接口

**Comment by yidasanqian** [comment]
180.76.76.200 和personalized这个接口没匹配到任何脚本，格则都是直连，应该是这个原因了
![940ba206d46d1d8a3511a1c444d1dee](https://user-images.githubusercontent.com/10655188/227092804-c1819b80-d7fd-4a33-8145-7caee3ac9d13.jpg)

**Comment by app2smile** [comment]
你是什么代理软件？是不是贴吧规则没引全。你看看主页的readme文档，少引入哪些

**Comment by yidasanqian** [comment]
> 你是什么代理软件？是不是贴吧规则没引全。你看看主页的readme文档，少引入哪些

引用的是loon的插件
![image](https://user-images.githubusercontent.com/10655188/227110858-42ec620e-cdb1-41ff-8189-8caa27a41d35.png)

**Comment by app2smile** [comment]
那可能是你的其他规则冲突了,  你手动添加一个180.76.76.200 的reject规则,  放在最前面

**Comment by yidasanqian** [comment]
我把180.76.76.200添加到hostname就可以了
