### ISSUE TITLE
哔哩哔哩首页展示数量

### ISSUE THREAD

**Issue by TaiPresident** [app2smile/rules#110]
感谢作者对哔哩哔哩脚本的维护，想问一下能不能将首页每次刷新的数量进行限制，去推荐时会出现一处空白，能否将推荐每次刷新限制成3✖️2或4✖️2

**Comment by app2smile** [comment]
空白位置就是去掉的广告, 每次刷新返回的推荐数量是b站动态返回的, 还不一样.
能不能控制还没研究过, 最近比较忙,可能没时间去研究

**Comment by TaiPresident** [comment]
谢谢🙏，希望有空的时候看一下，祝好
