### ISSUE TITLE
关于TK地区解锁模块与spotify模块冲突的问题

### ISSUE THREAD

**Issue by omgblack7** [app2smile/rules#112]
ios16
Shadowrocket

TK和spotify两个软件分别使用对应模块使用都正常，唯独两个模块同时打开的时候就会出现spotify模块失效的情况，不知道两个模块冲突有什么解决方法。

美国模块https://raw.githubusercontent.com/Semporia/TikTok-Unlock/master/Shadowrocket/TiKTok-US.conf
spotify破解模块https://raw.githubusercontent.com/app2smile/rules/master/plugin/spotify.plugin

**Comment by app2smile** [comment]
换其他代理软件试试, 现在无法确定是代理软件问题还是你的配置问题.
我这边surge日常也加载有这两个模块, 但是正常使用没问题

**Comment by Light8r** [comment]
我也出现了相同的问题，shadowrocket 2.2.29（1927 
tiktok29.2 
脚本相同 两者同时开启 Spotify脚本会失效

**Comment by Light8r** [comment]
Tiktok模块更换为Surge版本后问题解决
