### ISSUE TITLE
IOS，Spotify最新版不显示专辑歌曲列表，希望能修复一下

### ISSUE THREAD

**Issue by fan0424** [app2smile/rules#118]
如题，使用的圈x

**Comment by wqlu** [comment]
翻看下关闭的issue，一直都是不支持专辑歌曲列表的

**Comment by fan0424** [comment]
> 翻看下关闭的issue，一直都是不支持专辑歌曲列表的

原来一直不支持啊，懂了

**Comment by app2smile** [comment]
目前已支持, 更新看看 有问题请反馈

**Comment by fan0424** [comment]
> 目前已支持, 更新看看 有问题请反馈

测试过了，这次正常显示了，辛苦大佬！
