### ISSUE TITLE
Spotify歌词翻译，id和密钥输入正确，无法翻译显示请检查

### ISSUE THREAD

**Issue by Chilledwatermelon** [app2smile/rules#120]
代理软件quanx
![image](https://user-images.githubusercontent.com/100894819/233234735-c5e0e0d1-92d4-4790-b72a-759bae887dd5.png)

**Comment by app2smile** [comment]
52003这种情况就是appid配置有误或者服务未开通。这个错误码是百度返回的

**Comment by Chilledwatermelon** [comment]
> 52003这种情况就是appid配置有误或者服务未开通。这个错误码是百度返回的

**Comment by Chilledwatermelon** [comment]
谢谢，开发者，弄好啦，感谢您的付出

**Comment by tiancool** [comment]
同样的情况，QX，我已经在其他软件试过了，appid配置是可用的

**Comment by Elena-Xiao** [comment]
为什么我设置之后 每一首歌的歌词都无法加载了？

**Comment by xiaolugegege** [comment]
怎么弄的，我也是相同的情况

**Comment by Elena-Xiao** [comment]
> 怎么弄的，我也是相同的情况

把脚本放到本地文件圈叉的scripts里面，然后在圈叉上面添加重写就解决了，不要用远程引用

**Comment by ciclki** [comment]
![image](https://github.com/app2smile/rules/assets/152029247/e15cfb61-a896-457e-9f68-05bd7b812eef)我也是报52003能出个教程么？
