### ISSUE TITLE
Spotify 的premium界面来回跳出跟消失

### ISSUE THREAD

**Issue by yuan2333ace** [app2smile/rules#121]
这个问题导致排行榜的歌曲有时可以查看又是则不行  大佬这个问题可以优化吗？

**Comment by app2smile** [comment]
不太懂来回跳出是什么意思,  是premium的推广广告吗?

**Comment by yuan2333ace** [comment]
就是有时候右下角出现premium这种情况听不了排行榜的歌，过一会儿自动出现三个点刷新后premium就会消失。这种情况能解决吗？> 不太懂来回跳出是什么意思,  是premium的推广广告吗?

**Comment by yuan2333ace** [comment]
嗯嗯，用的quanx这种情况能解决吗？谢谢大佬回复

**Comment by yuan2333ace** [comment]
谢谢，我试着按以上三条排查下

**Comment by hjnhtt** [comment]
你解决了吗，我跟你情况一样> 谢谢，我试着按以上三条排查下

**Comment by blijiojiodiblidom** [comment]
现在不能下载歌曲了，可以解决下么？

**Comment by yuan2333ace** [comment]
我一直都不能下载

**Comment by hjnhtt** [comment]
你是怎么解决的> 好了 还会跳 频率比较少了> 你解决了吗，我跟你情况一样> 谢谢，我试着按以上三条排查下
> > 
> > 
> 
>

**Comment by hjnhtt** [comment]
> 把重写更新时间调到最小![image](https://github.com/app2smile/rules/assets/56262240/d5c7479c-7629-4569-9ad3-f79091f8c5c5)

我的一直都是48小时
