### ISSUE TITLE
spotify搜索艺人点击进去后是随机播放的建议

### ISSUE THREAD

**Issue by J-LiYongKang** [app2smile/rules#127]
因为作者还未实现搜索艺人里面的歌曲随意播放，我本人有点强迫症，看着界面觉得不是很舒服，所以我在使用spotify时候无意中发现一个spotify的小bug，就是当客户端和ios端同时登陆一个账户，播放设备设置为客户端的时候，搜索艺人的时候就能实现艺人界面的歌曲的播放，所以想问下作者是否可以利用这个bug实现此功能呢？
![微信图片_20230602003333](https://github.com/app2smile/rules/assets/60968098/cb9ed9f1-2b5f-4679-a2c8-33edb50cb43a)
![微信图片_20230602003341](https://github.com/app2smile/rules/assets/60968098/0ee156e6-895d-4706-aa73-6260a7e4e21b)

**Comment by app2smile** [comment]
好的 我研究研究

**Comment by app2smile** [comment]
模块已更新,  你更新下看看

**Comment by J-LiYongKang** [comment]
> 已模块更新,你更新下看看
不好意思 我才看到消息，确实可以用了，牛逼，感谢大佬！！
