### ISSUE TITLE
哔哩哔哩会出现动态页网络错误

### ISSUE THREAD

**Issue by imlxs** [app2smile/rules#128]
![image](https://github.com/app2smile/rules/assets/75208164/fa32a89f-87d2-4b71-a3e1-fda86a798850)

**Comment by app2smile** [comment]
提供详细信息。
用的什么代理软件？
是否开启了mitm h2？

最好开启抓包进行分析

**Comment by imlxs** [comment]
> 提供详细信息。
> 用的什么代理软件？
> 是否开启了mitm h2？
> 
> 最好开启抓包进行分析

用的小火箭，qx没问题

**Comment by app2smile** [comment]
不支持小火箭。
脚本只适配了surge 兼容loon，qx也应该支持

**Comment by imlxs** [comment]
好的
