### ISSUE TITLE
spotify解锁时专辑打开不显示歌曲

### ISSUE THREAD

**Issue by sinner7620** [app2smile/rules#129]
规则开启时，其他功能均正常但是打开专辑时显示的是未解锁的界面（不显示歌曲，只能随机播放）
试过安装旧版本，重启均无法解决（ios 16.4.1 版本：8.8.42）
![1](https://github.com/app2smile/rules/assets/62606659/805c7506-3d4c-4715-bdee-5229ad8040fc)

**Comment by app2smile** [comment]
目前不支持该功能。

**Comment by sinner7620** [comment]
> 目前不支持该功能。

iPhone上一直不可以显示吗？但是我ipad上是可以显示的，奇怪。难道是ipad版的app才行吗

**Comment by app2smile** [comment]
iphone上不可以, iPad版本我没研究过

**Comment by app2smile** [comment]
改天我登陆iPad试试

**Comment by sinner7620** [comment]
> iphone上不可以, iPad版本我没研究过

![IMG_3870](https://github.com/app2smile/rules/assets/62606659/0e964fc8-906b-4dbe-a830-d55b015d7a6d)
我之前一直用ipad，没发现iPhone上不可以看专辑
（这样确实不太方便）

**Comment by app2smile** [comment]
好的 感谢反馈 我研究研究

**Comment by app2smile** [comment]
此问题已处理 请更新模块后, 查看歌手 /专辑是否可正常显示并播放歌曲 

注意: 因为缓存的问题, 之前查看过的歌手/专辑数据不会重新请求会导致仍然查看不了. 解决办法可以删除app重新下载

**Comment by sinner7620** [comment]
> 此问题已处理 请更新模块后, 查看歌手 /专辑是否可正常显示并播放歌曲
> 
> 注意: 因为缓存的问题, 之前查看过的歌手/专辑数据不会重新请求会导致仍然查看不了. 解决办法可以删除app重新下载

感谢大佬，可以显示了！但是打开要加载好久，不清楚是什么原因
![2](https://github.com/app2smile/rules/assets/62606659/ee57ef51-4b6e-4ccf-91e2-ffa3ef641a67)
![3](https://github.com/app2smile/rules/assets/62606659/00d84601-84e7-4884-9bf8-b8e5a5e90ea1)

**Comment by app2smile** [comment]
哪个页面加载时间久?

**Comment by app2smile** [comment]
我这边专辑和歌手页面是秒开的.  你可以查看一下脚本日志 或者代理软件的系统日志 看看是脚本执行的慢还是怎么的?

**Comment by app2smile** [comment]
qx的有点问题 刚更新了 ,你用的是不是qx? 是的话可以再更新一下

**Comment by sinner7620** [comment]
> 我这边专辑和歌手页面是秒开的. 你可以查看一下脚本日志 或者代理软件的系统日志 看看是脚本执行的慢还是怎么的?

可以帮忙瞅一眼吗
![IMG_0234](https://github.com/app2smile/rules/assets/62606659/3415d0bf-483d-46c7-8eb8-dd55dfbbde75)

**Comment by sinner7620** [comment]
更新之后又失效了

**Comment by sinner7620** [comment]
> qx又更新了一下 你再试试

好了，完美！谢谢谢谢辛苦了
