### ISSUE TITLE
Spotify 突然无法登陆了

### ISSUE THREAD

**Issue by chk970222** [app2smile/rules#131]
今天打开Spotify 突然要求重新登陆，然后一直无法登陆，重新安装app也不行。ios16.5,qx,看了下在网络活动里提示这个，请看看是怎么回事，谢谢，万分感谢。
![IMG_4075](https://github.com/app2smile/rules/assets/17904178/875a069a-59f0-4f7f-96fc-480d0fa5fc1b)
![IMG_4076](https://github.com/app2smile/rules/assets/17904178/427bf01e-fc12-4b41-a1cc-5e00778129e3)

**Comment by chk970222** [comment]
网络是通的

**Comment by app2smile** [comment]
这是你代理软件上配置的一些规则拦截了spotify的网络请求。

你找到对应的规则删掉即可。

**Comment by chk970222** [comment]
哦哦，好的谢谢，我去找找，都没弄过其他的呀。
