### ISSUE TITLE
贴吧去广告

### ISSUE THREAD

**Issue by spirytuslove** [app2smile/rules#132]
大佬我翻了下贴吧去广告的失效情况  好像去广告失效是得看下有没有冲突的规则对吧  我现在的日志能不能帮忙分析下为啥会失败。。。

**Comment by spirytuslove** [comment]
![Uploading IMG_7231.png…]()

**Comment by spirytuslove** [comment]
![Uploading IMG_7232.png…]()

**Comment by spirytuslove** [comment]
![IMG_7230](https://github.com/app2smile/rules/assets/64483414/f4653e78-2903-4533-a15a-207c44715c04)

**Comment by spirytuslove** [comment]
![IMG_7232](https://github.com/app2smile/rules/assets/64483414/7ea990fa-7edc-426d-8734-e13b035a0765)
![IMG_7231](https://github.com/app2smile/rules/assets/64483414/d341e80b-da0e-47ca-b90b-9f2d990ee6af)

**Comment by app2smile** [comment]
没看到你的sync接口 你这个不是贴吧的sync接口

**Comment by spirytuslove** [comment]
大佬你在看下是不是这个最近请求
![IMG_7261](https://github.com/app2smile/rules/assets/64483414/13e15ad2-7ac4-496c-8128-4a0df78f1106)
![IMG_7260](https://github.com/app2smile/rules/assets/64483414/1126ec42-b01f-42c1-9c04-b7453ce0f115)

**Comment by app2smile** [comment]
最下面的那俩sync 你可能加载的有其他的规则把它屏蔽了。不能屏蔽

**Comment by spirytuslove** [comment]
感谢回复 这要怎么排查啊

**Comment by spirytuslove** [comment]
而且我mitm 180这个域名一直显示的是失败 把贴吧缓存清了再进去第一次会有点效果 一刷新前面横幅广告都出来了

**Comment by app2smile** [comment]
180无需mitm，只要你正常引入模块是没问题的。因为模块会屏蔽180请求

第一次有效后续无效是因为sync被屏蔽了导致后续无效

**Comment by spirytuslove** [comment]
感谢回复 大佬我用的surge 之前圈叉没问题 现在surge要怎么排查冲突规则啊

**Comment by app2smile** [comment]
点开sync这条请求，会显示这个请求匹配到了哪个规则或者脚本。

**Comment by spirytuslove** [comment]
![IMG_7302](https://github.com/app2smile/rules/assets/64483414/a6bb8048-50ce-4372-a41b-48a87e930d67)
这是匹配了拒绝的规则吗 要搜索重写里面哪一条

**Comment by app2smile** [comment]
你只能把你加载的规则链接一个个在电脑打开，然后查看

**Comment by spirytuslove** [comment]
我刚试了把重写里面规则都删了 然后再开贴吧 发现还是里面的贴片广告没去掉

**Comment by app2smile** [comment]
行不行 看日志的

**Comment by spirytuslove** [comment]
大佬有一个奇怪现象 我把重写开关关了 立马贴吧就没广告了 开了重写开关 就算把里面规则都删了还是会有广告 只有把重写开关关了才没有

**Comment by app2smile** [comment]
这说明是你加载的别人有个重写有问题

**Comment by spirytuslove** [comment]
那这我要怎么处理 是换个配置吗 还是现在原有配置也可以改

**Comment by spirytuslove** [comment]
解决了 把我一个引用的模块换了就可以了 感谢
