### ISSUE TITLE
翻译插件没有报错，但是好像没有效果

### ISSUE THREAD

**Issue by Alex-WU-Gen-9-png** [app2smile/rules#135]
![](https://img.urlnode.com/file/ef41b25dec83af19bcdb5.jpg)
这样是起效果了吗？
我好像之前看到过左上角有翻译按钮，但现在没有了，而且那个不是官方的插件吗？
可联系[tg](https://t.me/misaka_masters)

**Comment by app2smile** [comment]
翻译按钮是官方的样式.  插件的作用是无翻译的时候带上翻译. 你需要先看看如surge的脚本日志 看看翻译脚本执行了没有
