### ISSUE TITLE
spotify 新版本(8.8.58.450)更新之后,使用解锁脚本时，无法播放音乐

### ISSUE THREAD

**Issue by jyucoeng** [app2smile/rules#139]
spotify 新版本(8.8.58.450)更新之后,使用圈x的解锁脚本时，无法播放音乐，出现了歌曲不停切换的情况，关闭圈x之后，打开spotify，能正常播放歌曲(虽然出现了premium)。麻烦开发者看一下。 thanks

**Comment by app2smile** [comment]
盲猜你开启了超高音质

**Comment by jyucoeng** [comment]
> 盲猜你开启了超高音质

感谢提醒,试了，果然是的。
