### ISSUE TITLE
希望大神写个小白配置，把你的模块和js集成进去！  小白还是比较多的。比如我一直搞不懂surge

### ISSUE THREAD

**Issue by lijing-love** [app2smile/rules#14]

**Comment by app2smile** [comment]
建议先在surge官方文档中学习一下surge软件的使用规则和配置. 
本项目给出的链接已经是最精简过的模块了,直接引入加载就可以.

如果对软件使用不明白,单独加载本项目的模块 也可能会出现不生效,自己不知道如何排查问题的情况.

**Comment by lijing-love** [comment]
好的！感谢大神🙏
