### ISSUE TITLE
新版本好像解锁失效，清除缓冲重新登陆

### ISSUE THREAD

**Issue by kityeungfe** [app2smile/rules#140]
尝试登录和清除缓存几次，还是没有破解，是新版本不适用了吗？
![IMG_6574](https://github.com/app2smile/rules/assets/111792923/58c3e8ac-24b8-4fff-ad94-37f227d10e6c)

**Comment by wqlu** [comment]
我昨天也遇到这个情况，版本是`8.8.60.501`

**Comment by liuye1103** [comment]
> 我昨天也遇到这个情况，版本是`8.8.60.501`

能给个联系方式吗，请教下

**Comment by app2smile** [comment]
无法重现

**Comment by wqlu** [comment]
> > 我昨天也遇到这个情况，版本是`8.8.60.501`
> 
> 能给个联系方式吗，请教下

我更新了一下到最新版本`8.8.62.549`，可以用了，但是下面的Premium tab不像之前那些去除了。

**Comment by wqlu** [comment]
没啥问题，检查后发现自己重写规则忘开了
