### ISSUE TITLE
qx贴吧去广告的filter失效

### ISSUE THREAD

**Issue by shockwire5** [app2smile/rules#144]
似乎qx贴吧去广告的filter失效了，开屏广告无法屏蔽

**Comment by app2smile** [comment]
这种情况一般是自己规则冲突的问题.  贴吧有个sync的接口, 你搜搜 不能被屏蔽.

**Comment by shockwire5** [comment]
> 这种情况一般是自己规则冲突的问题.  贴吧有个sync的接口, 你搜搜 不能被屏蔽.

是哪个贴吧呢？感谢

**Comment by app2smile** [comment]
打开你的qx, 开启抓包 然后重新打开贴吧.  抓到包后在qx搜索sync即可

**Comment by shockwire5** [comment]
> 打开你的qx, 开启抓包 然后重新打开贴吧.  抓到包后在qx搜索sync即可

这个sync接口我没用过，不是很确定怎么操作，有相关教程吗？

**Comment by app2smile** [comment]
这不是你用的接口. 是贴吧用的. 这个操作属于qx软件的使用操作, 包括排查规则的冲突这些, 你需要上网找找qx的进阶操作
