### ISSUE TITLE
Spotify 歌词翻译 有概率 翻译失败

### ISSUE THREAD

**Issue by 0daysseus** [app2smile/rules#148]
报错内容是：
[JS exception]:TypeError: undefined is not an object (evaluating 'e.length')

**Comment by app2smile** [comment]
好的，我排查一下

**Comment by app2smile** [comment]
spotify的歌词现在有点迷, 部分之前能获取到歌词的歌曲现在无法获取到, 所以脚本报错了. 现在改为获取不到就不翻译
