### ISSUE TITLE
bilibili模版每次打开b站都会弹出错误通知

### ISSUE THREAD

**Issue by Meonthb** [app2smile/rules#15]
bilibili模版每次打开b站都会弹出错误通知
![](https://i.imgur.com/HofP3xp.jpg)

**Comment by app2smile** [comment]
加载模块的前提下，更新一下模块和外部js文件试试

**Comment by Meonthb** [comment]
> 加载模块的前提下，更新一下模块和外部js文件试试

现在好了，感谢大佬修复

**Comment by Meonthb** [comment]
> 加载模块的前提下，更新一下模块和外部js文件试试
大佬，打开视频时还是会弹出错误通知，不知道能否把这个错误通知取消改为日志提醒
![](https://i.imgur.com/dKYiYNy.jpg)

**Comment by Meonthb** [comment]
> 加载模块的前提下，更新一下模块和外部js文件试试

大佬，打开视频时还是会弹错误通知，不知道能否把这个错误通知取消改为日志提醒

![](https://i.imgur.com/dKYiYNy.jpg)

**Comment by app2smile** [comment]
有没有复现步骤呢？ 下午了我看一下

**Comment by app2smile** [comment]
我记得日志会有详细输入 可以复制贴出来

**Comment by app2smile** [comment]
> > 加载模块的前提下，更新一下模块和外部js文件试试
> 
> 大佬，打开视频时还是会弹错误通知，不知道能否把这个错误通知取消改为日志提醒
> 
> ![](https://camo.githubusercontent.com/4dbd29ec3086a24e6b9c0d68ea7fa1a413bca26ed0c8a084a3a657b31db40662/68747470733a2f2f692e696d6775722e636f6d2f644b5969594e792e6a7067)

这个是怎么操作出来的? 我这边操作不出来

**Comment by app2smile** [comment]
找到问题了,有个路径被正则误拦截了,你更新一下模块

**Comment by Meonthb** [comment]
> 找到问题了,有个路径被正则误拦截了,你更新一下模块

现在可以了
