### ISSUE TITLE
spotify歌词

### ISSUE THREAD

**Issue by BlackSpacee** [app2smile/rules#151]
大佬，用你的解锁和翻译很久了，一直都很好用，最近歌词有点不太好用了，大多数英文歌无法翻译，关了歌词翻译功能也无法翻译，清除缓存也没辙（QuanX），是不是因为无套餐用户。因为我最近看到消息说测试只有会员用户才能有歌词这么一说，歌词要收费什么的。spotify最近在测试的功能。那以后怎么办呐。

**Comment by app2smile** [comment]
这个我最近也遇到过 有的可以翻译有的请求歌词直接就报错 无法请求歌词，暂不明白具体原因。
至于歌词以后是不是会员功能，现在也不清楚。
