### ISSUE TITLE
贴吧的我的页面

### ISSUE THREAD

**Issue by YxFeb** [app2smile/rules#154]
大佬您好 我写了个针对贴吧的我的页面的去广告 不知道您能否整合进去

^https:\/\/tiebac\.baidu\.com\/c\/u\/user\/profile$ url script-response-body tieba-user.js

var body = $response.body;
var json = JSON.parse(body);

// 过滤掉特定关键词的对象
if (json.hasOwnProperty("vip_banner")) {
    delete json["vip_banner"];
}
if (json.hasOwnProperty("namoaixud_entry")) {
    delete json["namoaixud_entry"];
}
if (json.hasOwnProperty("duxiaoman_entry")) {
    delete json["duxiaoman_entry"];
}
if (json.hasOwnProperty("banner")) {
    delete json["banner"];
}
if (json.hasOwnProperty("recom_naws_list")) {
    delete json["recom_naws_list"];
}

// 过滤掉"user"中的"user_growth"
if (json.hasOwnProperty("user") && json["user"].hasOwnProperty("user_growth")) {
    delete json["user"]["user_growth"];
}

$done({ body: JSON.stringify(json) });

**Comment by app2smile** [comment]
不好意思太久才上来看。最近太忙了，需要等不忙的时候才能搞😂
