### ISSUE TITLE
Spotify翻译问题

### ISSUE THREAD

**Issue by Akimio521** [app2smile/rules#156]
使用Loon部署
![image](https://github.com/app2smile/rules/assets/77880495/bc829793-5de9-4bb2-98dc-092d23f45490)
![image](https://github.com/app2smile/rules/assets/77880495/ce56095d-e4e5-4eec-85f7-309762072d14)
在iPhoneXR ios16.1.2上出现这一问题
但是在使用同一配置的iPad Pro 2018 iOS15.6上就正常
iPhone上有时会有翻译，但是翻译为英文并不是中文，而iPad上一直都是中文
**在Quan X也有类似的情况**

**Comment by Akimio521** [comment]
![image](https://github.com/app2smile/rules/assets/77880495/bb0baff8-ab05-4a51-81ed-392404d24cf0)
iPhone翻译成功但提示错误

**Comment by app2smile** [comment]
这错应该是请求超时 没遇到过。你换个代理软件再试试。
可能跟你的软件的规则配置有关

**Comment by Akimio521** [comment]
同样的配置文件，分流规则在ipad上就是正常的
