### ISSUE TITLE
Spotify歌词翻译问题：无法获取语言

### ISSUE THREAD

**Issue by Akimio521** [app2smile/rules#158]
如题，测试代理软件：quanx，loon
![image](https://github.com/app2smile/rules/assets/77880495/08cf5fe2-cee7-47e1-83fb-cea02c805614)![image](https://github.com/app2smile/rules/assets/77880495/ed1ea974-66a8-438e-a0e0-4ddc558b0f6d)

**Comment by app2smile** [comment]
一般是区域问题。你的是日区吗

**Comment by Akimio521** [comment]
对，是日区

**Comment by app2smile** [comment]
日区无法获取到语言，就这样。

**Comment by Akimio521** [comment]
还有这种说法的吗

**Comment by app2smile** [comment]
你换到美区就好了 之前有个也跟你一样
