### ISSUE TITLE
Spotify去广告和随机播放失败

### ISSUE THREAD

**Issue by Keratia** [app2smile/rules#160]
明明开了却说没有server之类的然后什么都没变咋解决啊大佬
![IMG_5884](https://github.com/app2smile/rules/assets/73972060/9bcd2f65-4428-4b4d-8e53-1ef816729ec9)
![IMG_5885](https://github.com/app2smile/rules/assets/73972060/0561ecb3-eb14-4aca-918a-9a1cc1d8f22d)

**Comment by Keratia** [comment]
这个不需要编辑配置么？本来的这个是链接点进去复制粘贴到rewrite就能直接用了吗？还是应该如何操作呢大佬，第一天用着实没头绪了啊

**Comment by Keratia** [comment]
这样的么
![Uploading IMG_5887.png…]()

**Comment by app2smile** [comment]
需要开启mitm

**Comment by Keratia** [comment]
找了个教程开了以后发现呃他不让我通过脚本诶大佬
![Uploading IMG_5890.png…]()

**Comment by app2smile** [comment]
先学学qx的操作吧。我没用qx 对他也不熟悉

**Comment by Keratia** [comment]
![1](https://github.com/app2smile/rules/assets/73972060/a77bc53a-ff90-44dd-bd0f-9c8c4a63d6b9)
好的主要是这个接触太少了我一时间也搜不到多少流程，多谢
