### ISSUE TITLE
spotify最新版脚本失效了

### ISSUE THREAD

**Issue by Godfox9527** [app2smile/rules#164]
手贱点了更新，作者可以更新下脚本适配最新版本吗😭

**Comment by app2smile** [comment]
支持最新版本 检查下脚本是否运行

**Comment by Godfox9527** [comment]
还真是，应该是脚本没生效，我用app manager 抹了数据再登陆就能用了，谢谢大佬回复

**Comment by Godfox9527** [comment]
> 支持最新版本检查下脚本是否运行

大佬，我这还是有问题，我现在只要重进spotify脚本就不执行，除非抹数据才可以执行脚本，再打开又失效，没更新之前从来都没出过这种情况，这是什么问题造成的呢，请问该怎么解决
