### ISSUE TITLE
Surge 在mac上使用 spotify 播放的广告还是无法屏蔽

### ISSUE THREAD

**Issue by Kmookay** [app2smile/rules#169]
Surge 在mac上使用 spotify 播放的广告还是没有屏蔽掉，在Iphone上使用 quant x 正常

**Comment by app2smile** [comment]
这个脚本没在mac上试过, 编写的时候也是针对iphone版本写的

**Comment by youngerruan** [comment]
> 这个脚本没在mac上试过, 编写的时候也是针对iphone版本写的

作者您好！一直在手机上使用您的脚本，想请问一下有没有计划对 mac 端 spotify也进行兼容哇？我目前开了 surge 模块，似乎是可以播放，显示专辑图片，但是软件界面有广告。

**Comment by app2smile** [comment]
> > 这个脚本没在mac上试过, 编写的时候也是针对iphone版本写的
> 
> 作者您好！一直在手机上使用您的脚本，想请问一下有没有计划对 mac 端 spotify也进行兼容哇？我目前开了 surge 模块，似乎是可以播放，显示专辑图片，但是软件界面有广告。

没有计划哇,因为本人不用

**Comment by Kmookay** [comment]
> > 这个脚本没在mac上试过, 编写的时候也是针对iphone版本写的
> 
> 作者您好！一直在手机上使用您的脚本，想请问一下有没有计划对 mac 端 spotify也进行兼容哇？我目前开了 surge 模块，似乎是可以播放，显示专辑图片，但是软件界面有广告。

你可以卸载重装下，应该是之前还没有开启脚本的时候，已经下载缓存了，我这边基本都是可以正常屏蔽的

**Comment by Kmookay** [comment]
在mac上也可以正常使用，关闭了
