### ISSUE TITLE
Spotify单个专辑页内的歌曲无法手动选择

### ISSUE THREAD

**Issue by fptetsunari** [app2smile/rules#17]
版主你好，特别感谢你做的Spotify规则，让整个app用下来整洁舒畅。不过，如题，单个专辑的歌曲无法手动选择，只能通过随机的形式播放，这样大大降低了自主性的乐趣。不知是否可以进行优化？辛苦啦，先在此拜谢
![CDC7CC7C-561A-4F07-AB26-2368515FB6A5](https://user-images.githubusercontent.com/58475418/142433951-25fac638-ee4f-4530-b66b-3f540b70a6f3.png)

**Comment by app2smile** [comment]
先手动搜索歌曲建播放列表 或者用歌单代替吧.

这个无法实现,因为数据是服务器下发的,会员下发的数据和普通用户是不一样的

**Comment by fptetsunari** [comment]
> 先手动搜索歌曲建播放列表 或者用歌单代替吧.
> 
> 这个无法实现,因为数据是服务器下发的,会员下发的数据和普通用户是不一样的

原来如此！版主辛苦啦
