### ISSUE TITLE
 spotify 现在 quanx 必须添加节点才可以用了吗

### ISSUE THREAD

**Issue by mymolasses** [app2smile/rules#170]
之前只添加了重写和mitm，开启后spotify 正常开启会员，一切正常

前段时间推给朋友，发现开启 quanx 后，spotify 网络就有问题，连啥都连不上，关了后是好的

我当时一切正常，手贱把 quanx 关了，然后发现情况跟他一样了

现在添加了机场的节点后，把 spotify 指向节点才正常

用的这个规则
https://github.com/sve1r/Rules-For-Quantumult-X/blob/main/Rules/Media/Foreign/Spotify.list

现在必须这样添加节点才可以用了吗

**Comment by app2smile** [comment]
这和解锁脚本无关. 脚本不会限制你的网络

**Comment by mymolasses** [comment]
确实，脚本是没啥问题的，有用quanx的老哥明白嘛，现在不添加节点不能用了嘛

**Comment by mymolasses** [comment]
> 这和解锁脚本无关. 脚本不会限制你的网络

我用surge是正常的，没有添加节点，只添加了模块，能够生效，但是quanx用的多，朋友只能用到quanx

**Comment by mymolasses** [comment]
还是和自身网络有关
自己在家wifi，路由器翻墙，quanx surge无节点都正常

用流量时候会出现这样，表现为spclient.wg.spotify.com同域名下其他请求无响应
比如  gabo-receiver-service/public/v3/events

**Comment by mymolasses** [comment]
上面如果有知道的老哥可以说下

close
