### ISSUE TITLE
关于Spotify翻译错误提示

### ISSUE THREAD

**Issue by 154766zyc** [app2smile/rules#173]

**Comment by app2smile** [comment]
你的密钥泄露了，尽快在百度翻译后台进行重置，防止别人盗用。

我不用qx，不太清楚qx怎么配置，建议你先去了解下qx的配置办法

**Comment by 154766zyc** [comment]
> 你的密钥泄露了，尽快在百度翻译后台进行重置，防止别人盗用。
> 
> 我不用qx，不太清楚qx怎么配置，建议你先去了解下qx的配置办法

就是圈X的配置方法不知道，看的很笼统，还是一知半解，谢谢提醒，只露了账户密钥没露
