### ISSUE TITLE
Spotify换区

### ISSUE THREAD

**Issue by Marcio2536** [app2smile/rules#18]
大佬能不能弄个Spotify换区的模组？菲律宾premium很多歌都听不了

**Comment by Marcio2536** [comment]
![image](https://user-images.githubusercontent.com/61924136/146630580-1045849f-b01c-4962-89f3-443ce6240680.jpeg)

**Comment by app2smile** [comment]
没时间研究这个,自己也没需求,就算研究出来也维护不了...
