### ISSUE TITLE
troubles with spotify.module

### ISSUE THREAD

**Issue by chevesco** [app2smile/rules#182]
please update the spotify.module to the latest Spotify version (the premium applies fine but none of the features works)

**Comment by lookoutmanjava** [comment]
i got the same problem,do u fix it?

**Comment by CubeShip** [comment]
+1，spotify vision 8.9.19.571

**Comment by IsabeIIe** [comment]
![IMG_5273](https://github.com/app2smile/rules/assets/43488490/93a6f3e2-bce3-43aa-b6e7-a18ae0b353ab)
打开脚本并且音质不是极高提示该页面😭大佬修复一下

**Comment by sailcom** [comment]
遇到同样的问题
+1

**Comment by app2smile** [comment]
我自己手机上最新版本是可用的。
但我没有其他账号测试 如果有遇到问题的可以联系我提供账号测试来让我修复此问题

**Comment by sailcom** [comment]
> 我自己手机上最新版本是可用的。 但我没有其他账号测试 如果有遇到问题的可以联系我提供账号测试来让我修复此问题

谢谢大佬，我已经解决此问题。
解决方案：卸载app，重新安装并登录账号，脚本就可以生效了（只退出账号重新登录是没有用的）

**Comment by SoiGitRepo** [comment]
https://github.com/app2smile/rules/issues/182#issuecomment-2051962730

试过了不行，我用的是圈X，日区下载的Spotify，然后通过Facebook帐号登录Spotify，依旧弹窗不给播放，有点难搞

**Comment by CubeShip** [comment]
> 我自己手机上最新版本是可用的。 但我没有其他账号测试 如果有遇到问题的可以联系我提供账号测试来让我修复此问题

现在没问题了，感谢

**Comment by youw3** [comment]
> > 我自己手机上最新版本是可用的。 但我没有其他账号测试 如果有遇到问题的可以联系我提供账号测试来让我修复此问题
> 
> 
> 
> 谢谢大佬，我已经解决此问题。
> 
> 解决方案：卸载app，重新下载安装app并登录账号，脚本就可以生效了（只退出账号重新登录是没有用的）

还是不行呀

**Comment by yanh8761** [comment]
> > 我自己手机上最新版本是可用的。 但我没有其他账号测试 如果有遇到问题的可以联系我提供账号测试来让我修复此问题
> 
> 
> 
> 谢谢大佬，我已经解决此问题。
> 
> 解决方案：卸载app，重新下载安装app并登录账号，脚本就可以生效了（只退出账号重新登录是没有用的）

跟你同样的问题，但是卸载以后重新安装也不行，还有没有其他操作，谢谢！

**Comment by youw3** [comment]
> > > 我自己手机上最新版本是可用的。 但我没有其他账号测试 如果有遇到问题的可以联系我提供账号测试来让我修复此问题
> > 
> > 
> > 
> > 谢谢大佬，我已经解决此问题。
> > 
> > 解决方案：卸载app，重新下载安装app并登录账号，脚本就可以生效了（只退出账号重新登录是没有用的）
> 
> 跟你同样的问题，但是卸载以后重新安装也不行，还有没有其他操作，谢谢！

我这边已经可以了，你现在试试，感谢作者大大和各位

**Comment by sailcom** [comment]
> > > 我自己手机上最新版本是可用的。 但我没有其他账号测试 如果有遇到问题的可以联系我提供账号测试来让我修复此问题
> > 
> > 
> > 谢谢大佬，我已经解决此问题。
> > 解决方案：卸载app，重新下载安装app并登录账号，脚本就可以生效了（只退出账号重新登录是没有用的）
> 
> 跟你同样的问题，但是卸载以后重新安装也不行，还有没有其他操作，谢谢！

我不知道您用的是什么软件。我用的小火箭，所以只能确认在小火箭是正常使用的。
如果您的小火箭安装了这个模块还是不生效，建议你检查是否存在以下几种问题：
1. 检查一下对应的这个模块是否已经启用（在配置--模块列表里，对应的模块要打上对勾）；
2. 检查所有模块中的[mitm]部分，hostname = 后面必须要加 %APPEND%，否则模块之间可能会互相干扰导致失效；
3. 配置中的https解密是否打开，是否安装了证书，且已被系统信任，且已启用；
4. 确保代理的稳定性，尽量不要反复跳ip；
5. 如果还是不行，可以看一下实时日志（小火箭实时日志可在局域网访问 http://192.168.68.81:1082/api/log ），看看进入spotify时，是否有相关的日志信息，以此排查原因。

**Comment by chevesco** [comment]
fixed by changing region on spotify.com

**Comment by chevesco** [comment]
fixed

**Comment by chevesco** [comment]
fixed by changing region on spotify.com

**Comment by chevesco** [comment]
remember to re-login into your account after changing
