### ISSUE TITLE
贴吧模块导致贴内用户名不显示

### ISSUE THREAD

**Issue by Rubinart** [app2smile/rules#183]
使用贴吧去广告模块后，最新版贴吧12.58.1的贴内用户名不显示。
![IMG_5150](https://github.com/app2smile/rules/assets/100084120/33306bfc-8c1b-4fde-8318-d28a1819854e)

**Comment by Rubinart** [comment]
不知道大佬能不能修复这个问题，不胜感激

**Comment by Godfox9527** [comment]
同问题

**Comment by app2smile** [comment]
我天天用贴吧，但这两天手机没自动更新，刚发现这个问题，已经更新修复了
