### ISSUE TITLE
You discovered a premium feature

### ISSUE THREAD

**Issue by giterwen** [app2smile/rules#186]
![image](https://github.com/app2smile/rules/assets/17942997/7af89b43-9d9d-411c-9f13-8f4ffe966e86)![image](https://github.com/app2smile/rules/assets/17942997/93c15b90-c78a-4e94-aadc-2a3c9328aba6)
QuantumultX日志报错如图所示，卸载重新安装还是复现

**Comment by app2smile** [comment]
如果会抓包,可以关闭脚本后, 抓取 user-customization-service/v1/customize 这个请求的响应, 发上来让我分析一下

**Comment by giterwen** [comment]
> 如果会抓包,可以关闭脚本后, 抓取 user-customization-service/v1/customize 这个请求的响应, 发上来让我分析一下

是这个么
![image](https://github.com/app2smile/rules/assets/17942997/c3e0e0ed-caa5-4c11-89f6-e4d3d5758479)

**Comment by giterwen** [comment]
关闭了脚本是这个
![image](https://github.com/app2smile/rules/assets/17942997/460fd83e-a19f-47cd-bc6c-7546830d6397)
执行了一遍是这个
![image](https://github.com/app2smile/rules/assets/17942997/c81c55a4-5d77-4e52-af92-e12a00a423ed)

**Comment by app2smile** [comment]
你这个是返回304了,  我没其他测试帐号 暂不清楚什么情况下会返回304?

**Comment by app2smile** [comment]
你可以关闭脚本,卸载重装后再抓包一次 避免缓存的情况

**Comment by giterwen** [comment]
> 你可以关闭脚本,卸载重装后再抓包一次 避免缓存的情况

![image](https://github.com/app2smile/rules/assets/17942997/8779c5f8-ab60-4e49-b00c-35172fcf1e17)
这是清除缓存后卸载重装的结果
![image](https://github.com/app2smile/rules/assets/17942997/68331402-ba86-4f8b-aac3-bffe3787b799)
这是再次执行的截图

**Comment by app2smile** [comment]
截图看不出来啥 需要把响应的结果导出来, 上传到这里

**Comment by app2smile** [comment]
![image](https://github.com/app2smile/rules/assets/34903735/b1468155-ec1c-4694-9d07-a7d5c00a44c1)

**Comment by giterwen** [comment]
@app2smile 好的 晚上回去传下

**Comment by giterwen** [comment]
@app2smile 
[Uploading data.txt…]()

**Comment by giterwen** [comment]
> @app2smile 原生导出的不带.txt后缀 需要去掉 Uploading data.txt…

貌似没传上去，看下这个https://github.com/giterwen/Util/blob/main/data.txt

**Comment by app2smile** [comment]
好的 我分析一下

**Comment by app2smile** [comment]
你上传的这个我分析了一下没发现报错 ,你再开启脚本试试?

**Comment by giterwen** [comment]
> 你上传的这个我分析了一下没发现报错 ,你再开启脚本试试?

开启脚本重新试了还是不行，文件还是这个链接，已覆盖更新上传

**Comment by app2smile** [comment]
已查看 但没实际帐号无法定位问题解决,  可以联系我的tg 就是这个用户名
