### ISSUE TITLE
贴吧去广告 加载后  所有吧都无法看到内容了 如图

### ISSUE THREAD

**Issue by betakernel** [app2smile/rules#188]
![微信图片_20240503083744](https://github.com/app2smile/rules/assets/26702704/0cefd71f-9d2b-4915-93a2-43f656576278)

求更新

**Comment by 403page** [comment]
是的，我这里遇到同样问题。
帖子列表加载不出来，但是具体的帖子能点进去

**Comment by app2smile** [comment]
发下脚本日志 才能定位问题

**Comment by 403page** [comment]
我这边的日志是这样

2024/05/06 17:24:19:310  <console>    [JS Console]: 2024-04-12
2024/05/06 17:24:19:358  <console>    [JS Console]: 贴吧-personalized
2024/05/06 17:24:19:421  <console>    [JS Console]: 无推荐的直播帖子
2024/05/06 17:24:19:423  <console>    [JS Console]: 推荐页无banner广告
2024/05/06 17:24:19:440  <console>    [JS Console]: 89851---89851
2024/05/06 17:24:19:710  <console>    [JS Console]: 贴吧json-2023.06.12.2
2024/05/06 17:24:19:714  <console>    [JS Console]: 贴吧-sync
2024/05/06 17:24:19:715  <console>    [JS Console]: 右下角悬浮icon
2024/05/06 17:24:19:716  <console>    [JS Console]: 无需去除homepage悬浮
2024/05/06 17:24:19:717  <console>    [JS Console]: 无需去除pb悬浮
2024/05/06 17:24:19:719  <console>    [JS Console]: 无需处理advertisement_config
2024/05/06 17:24:19:720  <console>    [JS Console]: 禁止初始化platform_csj_init
2024/05/06 17:24:19:721  <console>    [JS Console]: 禁止初始化platform_ks_init
2024/05/06 17:24:19:722  <console>    [JS Console]: 禁止初始化platform_gdt_init
2024/05/06 17:24:19:724  <console>    [JS Console]: 开屏不展示小熊广告
2024/05/06 17:24:19:725  <console>    [JS Console]: 开屏不展示序章CPC
2024/05/06 17:24:19:726  <console>    [JS Console]: 开屏不展示序章
2024/05/06 17:24:19:727  <console>    [JS Console]: 修改ad_stlog_switch
2024/05/06 17:24:19:728  <console>    [JS Console]: 修改conn_conf
2024/05/06 17:24:24:795  <console>    [JS Console]: 2024-04-12
2024/05/06 17:24:24:798  <console>    [JS Console]: 贴吧-FrsPage
2024/05/06 17:24:24:866  <console>    [JS Console]: 无推荐的直播帖子
2024/05/06 17:24:24:869  <console>    [JS Console]: 无需处理activityhead
2024/05/06 17:24:24:889  <console>    [JS Console]: 64321---64321
2024/05/06 17:24:26:168  <console>    [JS Console]: 2024-04-12
2024/05/06 17:24:26:175  <console>    [JS Console]: 贴吧-FrsPage
2024/05/06 17:24:26:251  <console>    [JS Console]: 无推荐的直播帖子
2024/05/06 17:24:26:253  <console>    [JS Console]: 无需处理activityhead
2024/05/06 17:24:26:289  <console>    [JS Console]: 271565---271565

**Comment by app2smile** [comment]
看起来是没啥问题 推荐页能显示嘛? 只是吧内列表不展示?

**Comment by 403page** [comment]
首页推荐能刷出来，推荐的帖子也能点进去

**Comment by app2smile** [comment]
我这是好的, 你是用的什么工具

**Comment by 403page** [comment]
我用的圈X

**Comment by app2smile** [comment]
现在无法判断原因 我刚用Surge qx都试了  是可以的

**Comment by app2smile** [comment]
方便的话可以联系我提供帐号排查

**Comment by Ffuess** [comment]
我这也有同样的问题，用的surge。是贴吧app升级到最新版本后出现的问题

**Comment by 403page** [comment]
我这边莫名其妙又能刷出帖子了
不知是不是百度后台又搞了些什么

**Comment by yisaings** [comment]
我用的surge现在也出现了这种情况，看日志也没发现啥，不知道啥原因

**Comment by app2smile** [comment]
我怀疑是不同账户有不同的数据导致的.  需要有测试账户验证才能修复

**Comment by Sowaiwai** [comment]
> 我怀疑是不同的账户有不同的数据导致的。需要有测试账户验证才能修复

我可以提供

**Comment by Sowaiwai** [comment]
现版本往后退到12.59.1后恢复正常

**Comment by zhoujia3033** [comment]
我也遇到相同问题![image](https://github.com/app2smile/rules/assets/124252981/ebb4cbfb-ff35-4cc2-b133-d245f3ad4b34)更新后出现无法使用的情况，![image](https://github.com/app2smile/rules/assets/124252981/88cb7d5c-1142-4957-b88c-a42b19811400)

**Comment by zhoujia3033** [comment]
> 我怀疑是不同账户有不同的数据导致的.  需要有测试账户验证才能修复

有进展吗

**Comment by app2smile** [comment]
> > 我怀疑是不同的账户有不同的数据导致的。需要有测试账户验证才能修复
> 
> 我可以提供

可联系我的tg: app2smile 提供测试帐号

**Comment by Sowaiwai** [comment]
> > > 我怀疑是不同的账户有不同的数据导致的。需要有测试账户验证才能修复
> > 
> > 
> > 我可以提供
> 
> 可联系我的tg: app2smile 提供测试帐号

需要双向联系，sowaiwai

**Comment by zhoujia3033** [comment]
已解决，需要降级app版本

**Comment by app2smile** [comment]
> 已解决，需要降级app版本

下载新版本后 不登陆帐号能否正常进具体的吧看帖子?

**Comment by app2smile** [comment]
遇到问题的 可以开启抓包后 打开贴吧 浏览帖子后, 搜索c/s/sync接口  和 frs/page接口, 把抓包的数据导出来发在这里

**Comment by app2smile** [comment]
尝试更新了一下脚本的js 文件, 大家可以更新js文件后 再尝试一下

**Comment by Sowaiwai** [comment]
更新后可以正常进吧了
