### ISSUE TITLE
百度防跳转失败

### ISSUE THREAD

**Issue by zhizhishu** [app2smile/rules#19]
百度防跳转直接跳转到applestore了，是失效了吗？提示未能获取到tokendate

**Comment by app2smile** [comment]
不好意思,这个百度防跳转模块功能太简单,使用场景也比较狭窄,主要还是满足个人日常用的.

但是百度跳转的场景有很多,这个模块没有都做适配的,建议找找其他人的防跳转模块 
如果是iOS15系统还可以使用一些浏览器扩展来实现防跳转的功能.
