### ISSUE TITLE
Spotify似乎无法使用了

### ISSUE THREAD

**Issue by MaskPaperMan** [app2smile/rules#191]
第一个账号所有歌曲置灰
第二个新注册的账号无限跳转下一曲

作者大佬是否可以测试一下呢？可提供账号

**Comment by MaskPaperMan** [comment]
@app2smile 作者大佬是否可以测试一下呢？可提供账号

**Comment by kenny273** [comment]
最近账户名也变乱码，似乎是连接不上服务器了

**Comment by app2smile** [comment]
> @app2smile 作者大佬是否可以测试一下呢？可提供账号

可以联系我的tg 用户名就是app2smile

**Comment by MaskPaperMan** [comment]
感谢作者大佬，解决方法音质不设置超高即可
