### ISSUE TITLE
大佬，起点不跳转精选页好像失效了

### ISSUE THREAD

**Issue by mengdie101** [app2smile/rules#193]
日志显示无需处理，但实际还是跳转了
❚  起点-不跳转精选页
❚  无需处理,body:{"Data":{"ABTest":"B","AbType":"a","ActionUrl":"QDReader://Bookstore?query={\"abGroupId\": \"b\", \"lastReadBarEnabled\": \"1\"}","ActivityId":0,"BookId":0,"Channel":"activity","ChapterId":0,"DeepLinkType":5,"MaterialType":0,"MaterialTypeValue":"","ShareQImei":"","ShortUrl":"","ShowCount":0,"UserSource":5},"Message":"","Result":0}

**Comment by app2smile** [comment]
更新下脚本文件再试试
