### ISSUE TITLE
贴吧无法显示吧内主页的任何内容

### ISSUE THREAD

**Issue by shinmurakami1** [app2smile/rules#195]
![IMG_1617](https://github.com/app2smile/rules/assets/64008007/87af716a-0300-4b20-ad4b-dc0675c22482)
![IMG_1616](https://github.com/app2smile/rules/assets/64008007/033ea36b-23f8-4f73-8006-79eaf078b2be)
![IMG_1615](https://github.com/app2smile/rules/assets/64008007/6f865721-a91d-477b-a12b-347bb6ca78bf)
其他页面正常，版本12.61.3

**Comment by app2smile** [comment]
重复问题, 个人无法复现, 但有不少人反馈此问题.  
需要等我复现后才能解决

**Comment by app2smile** [comment]
更新了一下js文件

你更新脚本js后再试试
