### ISSUE TITLE
贴吧去除吧内帖子列表的直播失效

### ISSUE THREAD

**Issue by yemei123** [app2smile/rules#199]
版本12.65.1
![Uploading IMG_2758.jpeg…]()

**Comment by yemei123** [comment]
![IMG_2758](https://github.com/user-attachments/assets/cad763f2-b4a1-464c-b193-7cfa192611be)

**Comment by app2smile** [comment]
1. 用的是什么软件
2. 贴出日志看看

**Comment by yemei123** [comment]
1.圈x
2.
2024/07/26 11:56:59:642  <console>    [QTXLogHelper] iOS 16.7.2 (20H115) v1.5.0-build830 | log level - error.
2024/07/26 11:56:59:651  <console>    [QTXLogHelper] Processing cores 6.
2024/07/26 11:56:59:652  <console>    [QTXLogHelper] Physical memory 5.52 GB.
2024/07/26 11:56:59:687  <console>    [QTXLogHelper] Free storage 147.35 GB.
2024/07/26 11:56:59:688  <console>    [QTXLogHelper] Memory limit 50 MB.
2024/07/26 11:56:59:688  <console>    [QTXLogHelper] Initial memory footprint 2.00 MB.
2024/07/26 11:56:59:688  <console>    [QTXPacketTunnelProvider] 155B3FDBE68C.
2024/07/26 11:56:59:688  <console>    [QTXPacketTunnelProvider] Prefer outbound interface setting - 0.
2024/07/26 11:56:59:688  <console>    [QTXPacketTunnelProvider] Starting tunnel...
2024/07/26 11:56:59:777  <console>    [QTXLogHelper] Memory footprint 4.47 MB.
2024/07/26 11:56:59:777  <console>    [QTXPacketTunnelProvider] Tunnel started.
2024/07/26 11:57:13:766  <console>    [JS Console]: 贴吧json-2024.06.08
2024/07/26 11:57:13:771  <console>    [JS Console]: 贴吧-sync
2024/07/26 11:57:13:772  <console>    [JS Console]: 右下角悬浮icon
2024/07/26 11:57:13:773  <console>    [JS Console]: 无需去除homepage悬浮
2024/07/26 11:57:13:774  <console>    [JS Console]: 无需去除pb悬浮
2024/07/26 11:57:13:776  <console>    [JS Console]: 无需处理advertisement_config
2024/07/26 11:57:13:777  <console>    [JS Console]: 禁止初始化platform_csj_init
2024/07/26 11:57:13:778  <console>    [JS Console]: 禁止初始化platform_ks_init
2024/07/26 11:57:13:779  <console>    [JS Console]: 开屏不展示小熊广告
2024/07/26 11:57:13:780  <console>    [JS Console]: 开屏不展示序章CPC
2024/07/26 11:57:13:781  <console>    [JS Console]: 开屏不展示序章
2024/07/26 11:57:13:782  <console>    [JS Console]: 修改ad_stlog_switch
2024/07/26 11:57:13:783  <console>    [JS Console]: 修改conn_conf
2024/07/26 11:57:21:062  <console>    [JS Console]: 2024-06-08
2024/07/26 11:57:21:076  <console>    [JS Console]: 贴吧-FrsPage
2024/07/26 11:57:21:087  <console>    [JS Console]: app为空,无需处理
2024/07/26 11:57:21:089  <console>    [JS Console]: 去除帖子:直播2 / 视频0
2024/07/26 11:57:21:090  <console>    [JS Console]: 去除吧头直播
2024/07/26 11:57:21:092  <console>    [JS Console]: 无需处理activityhead
2024/07/26 11:57:59:974  <error>      [QTXTCPPath] The connection-214(153.35.88.48:80) through <DIRECT> closed: Connection refused
2024/07/26 11:58:00:019  <error>      [QTXTCPPath] The connection-222(153.35.88.48:80) through <DIRECT> closed: Connection refused
2024/07/26 11:58:00:068  <error>      [QTXTCPPath] The connection-223(153.35.88.48:80) through <DIRECT> closed: Connection refused
2024/07/26 11:58:30:363  <console>    [JS Console]: 2024-06-08
2024/07/26 11:58:30:376  <console>    [JS Console]: 贴吧-FrsPage
2024/07/26 11:58:30:384  <console>    [JS Console]: app为空,无需处理
2024/07/26 11:58:30:386  <console>    [JS Console]: 去除帖子:直播2 / 视频0
2024/07/26 11:58:30:387  <console>    [JS Console]: 去除吧头直播
2024/07/26 11:58:30:388  <console>    [JS Console]: 无需处理activityhead
![IMG_2761](https://github.com/user-attachments/assets/5e60e7cc-5a5f-42f8-92c8-ee952f0ed808)
![IMG_2760](https://github.com/user-attachments/assets/04dfb592-e547-4a79-877f-d5a911fbddb4)

**Comment by app2smile** [comment]
今天才复现此问题 已经修复了

你重新更新下资源文件
