### ISSUE TITLE
Spotify

### ISSUE THREAD

**Issue by XueTeng2** [app2smile/rules#20]
用了大佬的Spotify解锁脚本之后，发现Spotify可以解锁但是没有歌词，我的账户是台湾区的，正常情况下是有歌词的。是因为歌词和解锁是冲突吗？

**Comment by app2smile** [comment]
不是所有的歌曲都有歌词

**Comment by XueTeng2** [comment]
我试了三首歌，确认都是有歌词的，但是都没有显示，挂了台湾节点，打开了解锁脚本。

**Comment by app2smile** [comment]
说下歌名 这边测试一下

**Comment by XueTeng2** [comment]
罗大佑《皇后大道东》，梁静茹《偶阵雨》

**Comment by app2smile** [comment]
经过测试我这边有。你换个账号试试 看是账号问题还是网络问题

**Comment by XueTeng2** [comment]
> 经过测试我这边有。你换个账号试试 看是账号问题还是网络问题

好的，谢谢大佬！
