### ISSUE TITLE
Spotify锁屏播放问题

### ISSUE THREAD

**Issue by qianli-Koi** [app2smile/rules#21]
锁屏播放到30秒以后会有这两个请求，然后暂停播放![image](https://user-images.githubusercontent.com/83289881/150681813-98fe774c-b6d3-4fd3-8f41-d462946eab16.jpeg)

**Comment by app2smile** [comment]
自测未能还原,看看其他人是否也有此问题. 你可以先试试不走直连,走帐号所在区域的代理

**Comment by qianli-Koi** [comment]
> 自测未能还原,看看其他人是否也有此问题. 你可以先试试不走直连,走帐号所在区域的代理

我有个疑问就是，系统版本为什么一定要IOS15，是有什么区别吗

**Comment by app2smile** [comment]
> > 自测未能还原,看看其他人是否也有此问题. 你可以先试试不走直连,走帐号所在区域的代理
> 
> 我有个疑问就是，系统版本为什么一定要IOS15，是有什么区别吗

surge 和loon必须iOS15才能运行这个脚本, qx没有特别要求
