### ISSUE TITLE
随机播放（无法播放当前歌曲）

### ISSUE THREAD

**Issue by TaiPresident** [app2smile/rules#22]
![490242F0-40AB-459A-A37B-8004F8F04248](https://user-images.githubusercontent.com/76845019/150890567-32edcfcc-267e-4bd3-81a6-3790640446fa.jpeg)
每次点击播放后都是随机播放，无法播放当前歌曲

**Comment by app2smile** [comment]
点开模块链接,说明上有写,目前不支持专辑和歌手页面

**Comment by TaiPresident** [comment]
好的👌，谢谢🙏
