### ISSUE TITLE
关于Spotify A/B测试

### ISSUE THREAD

**Issue by adolphnov** [app2smile/rules#23]
Spotify经常放出测试的功能，例如界面样式变动，歌词翻译，图标更新等等。

请问是否有办法通重写将这些实验性功能放出？

---

![歌词翻译](https://user-images.githubusercontent.com/30210690/151208383-04774414-daec-4d1a-af36-eefa74de3da2.jpeg)

![新icon](https://user-images.githubusercontent.com/30210690/151208828-aa55bc3c-5e36-4e86-877f-a817b3cbb03f.jpeg)

**Comment by app2smile** [comment]
理论上可以,实际上需要有几个在不同测试组的帐号进行比对数据,才能编写脚本...

**Comment by adolphnov** [comment]
我小号也没有这些实验性功能😭，但是我发现切换帐号后，主页面右上角铃铛🔔会消失，底部半透明播放栏也会恢复为旧版，多次刷新又回来了。
可以尝试看看是否是哪个请求返回的控制的？我找找看有没有哪位朋友有实验性功能。

**Comment by yfue** [comment]
我没有歌词是怎么回事？用的英国节点，有没有哪位大佬指点一下

**Comment by adolphnov** [comment]
> 我没有歌词是怎么回事？用的英国节点，有没有哪位大佬指点一下

需要确定你的帐号是哪个区 按道理目前美区都有歌词了。
