### ISSUE TITLE
知乎8.6.0(8322)的搜索没法使用了

### ISSUE THREAD

**Issue by WoodyLin** [app2smile/rules#24]
Rt,使用最新去广告脚本无法使用搜索功能，麻烦大佬看下，谢谢

**Comment by app2smile** [comment]
可以抓包看下是为什么不能用，是哪个链接被屏蔽了还是怎么的。

把原因发出来便于分析。我测试加载模块的情况下用知乎搜索正常。

**Comment by WoodyLin** [comment]
> 可以抓包看下是为什么不能用，是哪个链接被屏蔽了还是怎么的。
> 
> 把原因发出来便于分析。我测试加载模块的情况下用知乎搜索正常。
大佬，这是知乎搜索test的抓包，麻烦看下
原始请求地址
https://api.zhihu.com/commercial_api/search_eggs?query=test
请求头
GET /commercial_api/search_eggs?query=test HTTP/1.1
Host: api.zhihu.com
X-Online-Host: api.zhihu.com
X-APP-BUILD-VERSION: 8322
x-close-recommend: 0
User-Agent: osee2unifiedRelease/8322 osee2unifiedReleaseVersion/8.6.0 Mozilla/5.0 (iPhone; CPU iPhone OS 15_3 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Mobile/15E148
X-EXPLORE: A
X-ZST-82: 2.0ALAeB_4scBQLAAAASwUAADIuMFoB_GEAAAAADFE8LizhSZ2zSR3lxSO0pHuHaSw=
X-Client-Ri: 2874249573
X-AD: canvas_version:v=5.1;setting:cad=0
Cookie: _xsrf=YBJSNJeTh0XqNDyvVvPlwzl9HvpOyzcb; z_c0=2|1:0|10:1643825967|4:z_c0|92:Mi4xd1NaZ0FBQUFBQUFBRUpMMDQyU0pFZ3NBQUFCZ0FsVk5MMWdpWWdEMHl5aXp0LTk0UGVNQTBXeHRRd2ZVcTQ1Rl9n|f25f2ed4d2cedcf2837739d992b04fe4f5a5e1351d713fdf4b2a02c32909d20d; q_c0=2|1:0|10:1643825967|4:q_c0|92:Mi4xd1NaZ0FBQUFBQUFBRUpMMDQyU0pFZ3NBQUFCZ0FsVk5MMWdpWWdEMHl5aXp0LTk0UGVNQTBXeHRRd2ZVcTQ1Rl9n|8692342c17fdd9ec7cc53dd5dea8f6748e9f1a5380e6971565a1f5bc39c1f1b3; _zap=72cdf2e1-0706-4db0-a6c5-e6fafb20ee5d; ariaDefaultTheme=undefined; d_c0=ABCS9ONkiRJLBfEqvGSIWvkhs5MXoaikxv0=|1643904582; zst_82=2.0ALAeB_4scBQLAAAASwUAADIuMFoB_GEAAAAADFE8LizhSZ2zSR3lxSO0pHuHaSw=; KLBRSID=019fe6991acde6c25995e7b271c1de42|1643905375|1643904581; q_c1=d7ffb96bf6fb40c5ac995412a3552d5f|1643826005000|1643826005000
Accept: */*
Accept-Encoding: gzip, deflate, br
x-app-bundleid: com.zhihu.ios
X-APP-ZA: OS=iOS&Release=15.3&Model=iPhone13,2&VersionName=8.6.0&VersionCode=8322&Width=1170&Height=2532&DeviceType=Phone&Brand=Apple&OperatorType=46001
X-Network-Type: WiFi
X-APP-VERSION: 8.6.0
Connection: keep-alive
X-Traffic-Free: 
x-custom-short-pin: 0
Authorization: Bearer 2.1wSZgAAAAAAAAEJL042SJEgsAAABgAlVNL1giYgD0yyizt-94PeMA0WxtQwfUq45F_g
X-AB-PB: CtYBDwubCz8GhALcC88LjATGBnsHRwB3B6YEFQXjBUMAaQECCAcHKQW3A6YG7AoqBn4G1gT6BqID9AtqAWAL2AdSC40EjAULBOQKGwA7AswC6QSiBoAFsgdAAecFEQWLBScHVAdmBwcMNAyrBvYC2gQBBtcLAQsqA3IHQQZ4BxYGwgVRBbkH2AJPAzIFmwc3BVYFNwzXAlYMowdPB7QKtADTB7ULMwUwBp4F4AsxBnkH9AN9AnQBuQLcBzID3QeUBlcHMwRXBOsG8wNSBT8AUAOJDKADsgWhAxJrAQAAAAAVBAAAAAAAAgAVAAIAAgEAAQAABAIAAAAAAAEEAQAAAAAAAAMAAAEAAAEAAAEBAAEBAAAAAAIBAAACAgEAAQEBAAAAAQABAQAAAAADAAABAAAAAgEBFQABAAABAAEAAAAAAAABCgA=
X-UDID: ABCS9ONkiRJLBfEqvGSIWvkhs5MXoaikxv0=
Accept-Language: zh-Hans-CN;q=1
x-ad-styles: bv_r_sp=4;creative_form=7;pmi_8_f_d=11;canvas_scene=2;pv_8_f_d=13;canvas_image=2;pv_30_d=9;bv_r_24=10;canvas_multilevel_choice=1;bsi_r_pu=16;canvas_viewpager=1;canvas_form=18;pv_314=2;pbi_8_r_c=1;canvas_video=1;bsi_r_z=4;pmi_8_f=11;bv_8_r_o=7;km_feed_01=3;canvas_text_choice=2;pmi_30=7;pii_31_d=2;canvas_phone_input=1;bv_f=20;sliding_8_r=1;pmi_30_d=5;pmi_8_r=11;pv_8_r_c=3;pw_8_f=14;pv_314_d=2;bv_r=21;canvas_page=3;bbi_r_24=10;bbi_31=1;bsi_f=17;pbi_8_f_d=11;pw_8_f_d=10;bw_r_z=4;creative_input=2;pw_8_r=19;pv_8_f=19;pbi_30=8;canvas_text=2;canvas_input=6;pii_8_f_d=9;bsi_r=31;psi_8_r_d=21;bbi_r_sp=4;pii_8_f=11;pbi_8_f=11;canvas_imagetext=1;bl_8_r_y=4;bv_r_z=7;pw_30_d=7;bp_r_24=10;pv_8_r=24;pmi_8_r_d=12;bw_30=5;pii_8_r=14;pbi_8_r=19;canvas_button=3;bv_8_f_o=3;canvas_choice=4;pv_8_r_d=18;pii_30=6;bl_8_r_n=2;canvas_sliders=1;bsi_h=37;creative_page=2;ps_8_f=5;psi_8_f=15;pbi_31=5;bv_30_i=6;canvas_follow_button=2;pl_8_r_y=5;pbi_30_d=5;bmi_30=6;bv_30_o=9;canvas_image_choice=2;ps_8_r=2;pbi_8_r_d=16;psi_8_r=20;bmi_f=15;pv_30=9;canvas_image_option=2;bw_8_f=9;pii_8_r_d=13;bmi_r=20;bbi_f=16;ba=5;psi_8_f_d=13;pl_8_r_n=2;canvas_text_option=2;pw_30=8;pw_8_r_d=15;bw_8_r=14;pii_31=3;creative_text=1;pii_30_d=5;bbi_30=10;pbi_31_d=2;bbi_r=22;
X-PACKAGE-YTPE: appstore
X-APP-BUILD: release
X-SUGER: VURJRD1BQkNTOU9Oa2lSSkxCZkVxdkdTSVd2a2hzNU1Yb2Fpa3h2MD07RElTSz0xMjc4NzA5ODAwOTY7TUVNTz04MTc3Nzk1MDcyO01PREVMPUQ1M2dBUDtTQlRTPTE2NDM4NzA3ODU7U1VUUz0xNjQzMjUzNDIyLjg4MzAwNDtETj05QTlDRjk3RThFMEIxRjQ3RjZDMDhCQUNFMjU4OUZBQztPUD3kuK3lm73ogZTpgJo7Q09VTlRSWT1DTjtMQU5HPXpoLUhhbnMtQ047VFo9Mjg4MDA7TUFDSElORT1pUGhvbmUxMywyO0FMSVNCVFM9MTY0Mzg3MDc4NS44MTkxODc7QUxJU1VUUz0xNjA5MjI2NjAxLjk2MTYwMDQxOztYLUFELUlQVjQ9MTcxLjgxLjE0NS4xMDE=
X-ZST-81: AODebAz-bhRQnG9XWuHVpd5yXpHasX-dw_dYfg==
X-API-Version: 3.1.8
x-ad-sps: 
x-zse-93: 101_2_1.0
x-zse-96: 1.0_nxL6VMw/3FpgQvo1w9xRKmOXlHY0f6ndDCduuJUAgfvlwcC2ESvQKBwFVhwMopY9
响应头
HTTP/1.1 200 OK
Server: CLOUD ELB 1.0.0
Date: Thu, 03 Feb 2022 16:22:56 GMT
Content-Type: application/json
Expires: Thu, 01 Jan 1970 08:00:00 CST
Pragma: no-cache
Vary: Accept-Encoding
X-Backend-Response: 0.007
Referrer-Policy: no-referrer-when-downgrade
X-SecNG-Response: 0.01200008392334
X-UDID: ABCS9ONkiRJLBfEqvGSIWvkhs5MXoaikxv0=
x-lb-timing: 0.013
x-idc-id: 2
Set-Cookie: KLBRSID=019fe6991acde6c25995e7b271c1de42|1643905376|1643904581; Path=/
Cache-Control: private, must-revalidate, no-cache, no-store, max-age=0
Content-Length: 3
X-NWS-LOG-UUID: 14226525604267341753
Connection: keep-alive
X-Cache-Lookup: Cache Miss
x-edge-timing: 0.037
x-cdn-provider: tencent
响应体
{}

**Comment by app2smile** [comment]
你抓错包了。![image](https://user-images.githubusercontent.com/34903735/152507329-1d09858d-9bc3-4bdb-bad8-0ce428133784.jpeg)

![image](https://user-images.githubusercontent.com/34903735/152507367-2fd6acd3-8935-4b1c-a18a-f4048ed6de8b.jpeg)

**Comment by WoodyLin** [comment]
qx好像没有这个🥲
![4640BDA8-A938-4E55-9AC3-52F200DB7745](https://user-images.githubusercontent.com/1460489/152516943-f6f49491-aa1d-499a-a8bb-40bafdfcf96b.jpeg)

**Comment by WoodyLin** [comment]
换了blackmatrix大佬的脚本可以正常搜索🥲
![ECCC3213-BB19-4ADB-A46A-D6211B4CD79E](https://user-images.githubusercontent.com/1460489/152631741-89dc0c7a-00e3-4077-b32b-33b5dfce0fd4.jpeg)


> 你抓错包了。![image](https://user-images.githubusercontent.com/34903735/152507329-1d09858d-9bc3-4bdb-bad8-0ce428133784.jpeg)
> 
> ![image](https://user-images.githubusercontent.com/34903735/152507367-2fd6acd3-8935-4b1c-a18a-f4048ed6de8b.jpeg)

**Comment by WoodyLin** [comment]
换了blackmatrix大佬的脚本好像就能正常请求图里面那一串……
![Uploading F4097016-6D67-4C32-B2DB-71514CE2EA4B.jpeg…]()

**Comment by app2smile** [comment]
先用别人的吧。这个去广告模块没测试qx和loon

**Comment by WoodyLin** [comment]
> 先用别人的吧。这个去广告模块没测试qx和loon

好的，还是谢谢大佬了~
