### ISSUE TITLE
关于推特广告

### ISSUE THREAD

**Issue by adolphnov** [app2smile/rules#25]
想请教大佬是否玩推？推特中feed里面很多推广广告，抓包分析不出🥲 大佬是否有时间尝试去除……

**Comment by app2smile** [comment]
twitter禁止mitm，无法去广告

**Comment by adolphnov** [comment]
原来如此，我还是用第三方app吧😥
2022年2月6日 +0800 17:59 app2smile ***@***.***>，写道：
