### ISSUE TITLE
B站去广告可以加上精简Tab么？

### ISSUE THREAD

**Issue by chaizia** [app2smile/rules#27]
大佬的去广告用起来很舒服，可以增加精简标签功能么？
![](https://gitee.com/chaizia/mypic/raw/master/2022/02/15/5ea6f0f93788c7fc4217fa11ea3c0197.png)
blackmatrix7以前有可惜停更了。

再次感谢，脚本很好，白嫖已久~ 3Q

**Comment by app2smile** [comment]
有的人要用会员购还有上传视频, 精简完之后这俩都没了

**Comment by chaizia** [comment]
嗯也是。目前把你脚本里注释掉的tab部分打开了在用着。ths
