### ISSUE TITLE
bilibili去广告有时会出现问题

### ISSUE THREAD

**Issue by Meonthb** [app2smile/rules#28]
开启bilibili去广告规则有时播放页面评论区无法加载，在这种情况下播放视频10秒左右视频会播放失败，必须重新刷新才能继续播放。

![](https://i.imgur.com/p10gFeg.png)

**Comment by app2smile** [comment]
是不是Surge

**Comment by Meonthb** [comment]
> 

是的

**Comment by Meonthb** [comment]
> 是不是Surge

是Surge

**Comment by app2smile** [comment]
Surge目前是有此问题的,loon和qx没有. 
暂不明确具体原因,只知道是在surge中此连接中断重连了.
