### ISSUE TITLE
起点脚本无故弹窗

### ISSUE THREAD

**Issue by Echo-FL** [app2smile/rules#29]
使用surge打开起点会跳这个弹窗

![816D2914-67E9-477D-A700-44EACC64B782](https://user-images.githubusercontent.com/56504601/155763308-834e08d1-d046-45e6-9394-76b09df6a791.png)

$notification.post(notifiTitle,"起点","Data/ActionUrl字段为undefined或者不为QDReader://Bookstore")}

**Comment by Echo-FL** [comment]
修改

**Comment by app2smile** [comment]
起点版本是多少呢？ 可以的话，在surge日志找到去广告日志，把错误详细贴出来

**Comment by Echo-FL** [comment]
> 起点版本是多少呢？ 可以的话，在surge日志找到去广告日志，把错误详细贴出来

起点版本：5.9.190

**Comment by Echo-FL** [comment]
22:13:47.790473 起点-iOS_tab
22:13:47.791410 返回配置空
22:13:47.792151 [Script Completed]
----------------------------
22:13:47.798623 起点-getconf
22:13:47.799932 ActivityPopup(活动弹窗)成功
22:13:47.801531 ActivityIcon成功
22:13:47.803001 允许搜索用户成功
22:13:47.804561 无需修改剪切板配置
22:13:47.805596 [Script Completed]
----------------------------
22:13:47.811444 起点-每日导读
22:13:47.812015 成功
22:13:47.812708 [Script Completed]
----------------------------
22:13:47.868797 起点-不跳转精选
22:13:47.870043 body:{"Data":{"ABTest":"B","AbType":"","ActionUrl":"","ActivityId":0,"BookId":0,"Channel":"","ChapterId":0,"DeepLinkType":0,"ShareQImei":"","ShortUrl":"","ShowCount":0,"UserSource":0},"Message":"","Result":0}
22:13:47.882528 [Script Completed]
----------------------------
22:13:48.049730 起点-getconf
22:13:48.050280 ActivityPopup(活动弹窗)成功
22:13:48.050870 ActivityIcon成功
22:13:48.051394 允许搜索用户成功
22:13:48.051909 无需修改剪切板配置
22:13:48.052922 [Script Completed]
----------------------------
22:13:48.186833 qq音乐-开屏页
22:13:48.187570 成功count:0
22:13:48.188361 [Script Completed]
----------------------------
22:13:58.019958 起点-getconf
22:13:58.020710 ActivityPopup(活动弹窗)成功
22:13:58.021322 ActivityIcon成功
22:13:58.021750 允许搜索用户成功
22:13:58.022450 无需修改剪切板配置
22:13:58.023275 [Script Completed]

> 起点版本是多少呢？ 可以的话，在surge日志找到去广告日志，把错误详细贴出来

**Comment by app2smile** [comment]
好的感谢。明天修一下
