### ISSUE TITLE
Spotify Station

### ISSUE THREAD

**Issue by clutchJoe** [app2smile/rules#30]
Spotify Station切歌无法解锁

**Comment by app2smile** [comment]
再详细描述一下你的情况：
脚本运行日志贴出来，先确认脚本运行了没有。
还有你app的截图，以及音质不能设置为超高。

**Comment by clutchJoe** [comment]
Spotify Stations上并没有音质设置

**Comment by clutchJoe** [comment]
![image](https://user-images.githubusercontent.com/36620073/155833779-7a71854c-b876-4c0b-8b9d-d33842251a9c.png)
![image](https://user-images.githubusercontent.com/36620073/155833793-1cc4342e-4ea0-47aa-87a7-f5926cd4e06d.png)
Spotify Stations没有设置音质的选项
