### ISSUE TITLE
qx去贴吧广告无效？

### ISSUE THREAD

**Issue by pingshu** [app2smile/rules#32]
![774B51C6-A89A-4175-BCE2-0CA49F7D14C7](https://user-images.githubusercontent.com/22138807/157156875-74f799c9-ab2a-4393-91d8-b76416207732.jpeg)

**Comment by app2smile** [comment]
贴吧哪个版本? 帐号登陆了吗? 发点更详细的日志或描述

**Comment by pingshu** [comment]
把qx改为规则分流就好了，谢谢
