### ISSUE TITLE
spotify可以下载到本地离线播放吗

### ISSUE THREAD

**Issue by closernow** [app2smile/rules#34]
如题。
尝试了一下，我用的quantum x 重写，查看账户好像是订阅用户了，但是下载专辑的时候出现一直转圈无法下载，可能是这个功能没有吧嘿嘿

**Comment by app2smile** [comment]
下载还不支持。目前也没时间再去研究下载的功能。😂

**Comment by kurtn2005** [comment]
> 下载还不支持。目前也没时间再去研究下载的功能。😂

大佬，Spotify超高音质有戏吗？

**Comment by app2smile** [comment]
> > 下载还不支持。目前也没时间再去研究下载的功能。joy
> 
> 大佬，Spotify超高音质有戏吗？

目前对标的是pc的功能,也没时间去搞这个超高音质,涉及会员收费功能有可能会导致帐号风险,得不偿失

**Comment by kurtn2005** [comment]
> > > 下载还不支持。目前也没时间再去研究下载的功能。joy
> > 
> > 
> > 大佬，Spotify超高音质有戏吗？
> 
> 目前对标的是pc的功能,也没时间去搞这个超高音质,涉及会员收费功能有可能会导致帐号风险,得不偿失

我手机上用可以，在Mac上用不行，打开模块会提示网络有问题，关闭模块就行了。
<img width="371" alt="图片" src="https://user-images.githubusercontent.com/23029247/165958340-542c1b9c-1512-417a-a1b3-e979c1469fc1.png">
