### ISSUE TITLE
小火箭使用Spotify模块报错

### ISSUE THREAD

**Issue by Coldvvater** [app2smile/rules#35]
具体报错内容：路径/请求方法匹配错误：
undefined,https://spclient.wg.spotify.com/
user-customization-service/v1/customize

<sub>Sent from <a href="https://apps.apple.com/cn/app/id1314212521">PPHub</a></sub>

**Comment by app2smile** [comment]
没有小火箭,没办法适配. 不知道小火箭支不支持解析二进制响应脚本

**Comment by Coldvvater** [comment]
> 没有小火箭,没办法适配. 不知道小火箭支不支持解析二进制响应脚本

但是我朋友的小火箭却可以用，没有报错

**Comment by XueTeng2** [comment]
我准备试试能不能修改一下大佬的代码把Spotify模块移植到Stash上面。

**Comment by FengTaoLi** [comment]
> > 没有小火箭,没办法适配. 不知道小火箭支不支持解析二进制响应脚本
> 
> 但是我朋友的小火箭却可以用，没有报错

解决了吗，怎么操作的，脚本这样应该没问题啊。
[Script]
spotify = type=http-response,script-path=https://raw.githubusercontent.com/app2smile/rules/master/js/spotify-proto.js,pattern=^https:\/\/spclient\.wg\.spotify\.com\/(bootstrap\/v1\/bootstrap|user-customization-service\/v1\/customize)$,max-size=131072,requires-body=true,timeout=10,enable=true

**Comment by junetwentytwo** [comment]
> 没有小火箭,没办法适配. 不知道小火箭支不支持解析二进制响应脚本

这个模块报错问题我咨询过小火箭开发者，得到的答复是：Shadowrocket 不支持 binary-body-mode，直接使用 $response.bodyBytes。但是不知道怎么改，不知道大佬能修改吗？

**Comment by Coldvvater** [comment]
> > 没有小火箭,没办法适配. 不知道小火箭支不支持解析二进制响应脚本
> 
> 这个模块报错问题我咨询过小火箭开发者，得到的答复是：Shadowrocket 不支持 binary-body-mode，直接使用 $response.bodyBytes。但是不知道怎么改，不知道大佬能修改吗？

小火箭更新后可以用了！

**Comment by shadycn** [comment]
额 能问问怎么设置小火箭spotify模块吗

**Comment by ly20190112** [comment]
老哥小火箭复制粘贴到哪里，还有需要手动选择的地方吗
