### ISSUE TITLE
添加Stash支持

### ISSUE THREAD

**Issue by XueTeng2** [app2smile/rules#37]
请问大佬能否为Stash添加Spotify解锁支持？我尝试按照Stash的Script格式引用大佬的代码写了个Spotify支持脚本，测试后发现没用，原来是大佬的代码不支持Stash。

**Comment by NrobEi** [comment]
同求。按stash格式添加代码到stash不起作用。

**Comment by eilse1** [comment]
是的，球球大佬

**Comment by app2smile** [comment]
没有Stash 而且也不知道stash支持不支持二进制脚本

**Comment by xiangsanliu** [comment]
附议😂

**Comment by XueTeng2** [comment]
> 没有Stash 而且也不知道stash支持不支持二进制脚本

Stash支持二进制脚本了

**Comment by app2smile** [comment]
> > 没有Stash 而且也不知道stash支持不支持二进制脚本
> 
> Stash支持二进制脚本了

有文档吗

**Comment by XueTeng2** [comment]
> > > 没有Stash 而且也不知道stash支持不支持二进制脚本
> > 
> > 
> > Stash支持二进制脚本了
> 
> 有文档吗

https://stash.wiki/features/override
大佬看看这个是吗

**Comment by app2smile** [comment]
文档上没看到支持二进制脚本的例子

**Comment by app2smile** [comment]
商店版还没更新 等商店版支持了会提供

**Comment by app2smile** [comment]
已更新,需要的可以自行尝试

**Comment by Single430** [comment]
> 已更新,需要的可以自行尝试

大佬你好，没有看到哪里有介绍可以使用stash？是我没有找到嘛

**Comment by app2smile** [comment]
进入仓库的module目录, 里面.stoverride后缀名的就是支持Stash的
[spotify-stash](https://raw.githubusercontent.com/app2smile/rules/master/module/spotify.stoverride)
