### ISSUE TITLE
起点去广告失败

### ISSUE THREAD

**Issue by Echo-FL** [app2smile/rules#38]
起点开屏界面偶尔还是会弹出广告

<sub>Sent from <a href="https://apps.apple.com/cn/app/id1314212521">PPHub</a></sub>

**Comment by app2smile** [comment]
遇到的话截图反馈,看看是什么广告.

另现在起点最新版本在使用过程中需要surge保持一直开启状态. 如果无法拦截也会出现广告.去广告脚本备注上有

**Comment by Echo-FL** [comment]
已解决
