### ISSUE TITLE
Spotify 偶尔回弹出 Premium 推广界面

### ISSUE THREAD

**Issue by isinglever** [app2smile/rules#39]
打开 Spotify 时可能会弹出 premium 推广界面，如图![image](https://user-images.githubusercontent.com/35318953/164909283-250affec-68ee-405c-8e2d-01ec682739cb.png)
查看 app 日志，发现有如下连接
```

apresolve.spotify.com:443

sharing-config.spotifycdn.com:443

dealer.spotify.com:443

ap-gae2.spotify.com:4070

api2.branch.io:443

spclient.wg.spotify.com:443

```

前面几个域名没有开启 MitM，不确定其他人有没有相同的问题，希望作者有时间再看看，谢谢作者，脚本很好用～

**Comment by afboyxiyang** [comment]
surge premium 一直显示

iOS15.5

还是会显示广告

**Comment by app2smile** [comment]
如果不影响正常听歌暂时先忽略掉
