### ISSUE TITLE
请教大佬，有些app用重写去广告后，广告没了，但是倒计时还在，请问这种有没有办法去掉倒计时？

### ISSUE THREAD

**Issue by 28413761** [app2smile/rules#40]
请教大佬，有些app用重写去广告后，广告没了，但是倒计时还在，请问这种有没有办法去掉倒计时？
比如浦大喜奔，民生银行，动卡空间，马卡龙玩图，
这些app去广告后的倒计时有什么办法能搞定它吗？

**Comment by app2smile** [comment]
有的倒计时不能去掉是空白, 有的app可以通过修改其他字段解决, 具体还得根据不同的app做相应处理

**Comment by 28413761** [comment]
请教大佬，比如浦大喜奔app的开屏广告，去掉广告后就是白板的倒计时，
中信银行app的开屏广告，去掉广告后就是透明的倒计时，
大佬有空的时候能帮忙看看这俩APP吗！
跪谢大佬！




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2022年4月26日(星期二) 中午11:11
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [app2smile/rules] 请教大佬，有些app用重写去广告后，广告没了，但是倒计时还在，请问这种有没有办法去掉倒计时？ (Issue #40)





 
有的倒计时不能去掉是空白, 有的app可以通过修改其他字段解决, 具体还得根据不同的app做相应处理
