### ISSUE TITLE
你好，起点最新版本去开屏页广告失效

### ISSUE THREAD

**Issue by yfue** [app2smile/rules#42]
使用的圈X最新tf版本，https://github.com/app2smile/rules/raw/master/module/qidian.conf

**Comment by app2smile** [comment]
看看有没有起点其他的脚本运行日志。一般是因为首次启动起点/后续使用中代理软件漏请求导致无法命中脚本的情况。qx只能删除重新下载起点解决

**Comment by yfue** [comment]
看了一下都是触发js了的，重装这些也试了。晚上回去试试surge看看有没有不同

**Comment by yfue** [comment]
感谢🙏🙏，没有了。感谢你的工作
