### ISSUE TITLE
大佬有空了能看看 携程， 飞猪旅行这俩app的开屏广告吗？

### ISSUE THREAD

**Issue by 28413761** [app2smile/rules#43]
这俩APP用得人也多，基本上刚需APP，
要么抓不到包，仓库抄来的规则也不太合适，
要么拦截不干净开屏广告，要么过渡拦截导致app里面很多图片无法正常加载.

**Comment by app2smile** [comment]
抱歉这么久才回复, 因个人精力有限,再加上不用这俩app 无法支持
