### ISSUE TITLE
添加贴吧相关的分流和重写之后加载特别慢，并且经常加载失败，这个如何解决

### ISSUE THREAD

**Issue by Allenj305** [app2smile/rules#44]

**Comment by app2smile** [comment]
目前贴吧脚本经过将近一年时间的验证运行非常稳定了，出现问题一般是自己配制的问题。可以提供一下更详细的描述帮你分析一下问题所在：

1.ios什么系统版本
2.贴吧什么系统版本
3.用的surge还是其他
4.运行脚本日志
5.请求链接的详细截图

**Comment by Allenj305** [comment]
> 目前贴吧脚本经过将近一年时间的验证运行非常稳定了，出现问题一般是自己配制的问题。可以提供一下更详细的描述帮你分析一下问题所在：
> 
> 1.ios什么系统版本
> 2.贴吧什么系统版本
> 3.用的surge还是其他
> 4.运行脚本日志
> 5.请求链接的详细截图
> 
> 

卸载重新安装之后正常了

**Comment by app2smile** [comment]
好的。
原则上来说，这个和卸不卸载没啥关联。
有时候脚本出问题可能是跟其他脚本有冲突导致的。

排查问题的时候去看最近请求和脚本运行日志都能发现问题。
