### ISSUE TITLE
贴吧去开屏广告失效

### ISSUE THREAD

**Issue by Meonthb** [app2smile/rules#45]
目前贴吧去广告模块开屏广告去除失败，可能是贴吧更新了广告策略

日志显示无异常，且确认网络环境正常

ios：15.5
surge：14.3.0
贴吧：12.24.3

![FCB9E35F-DED8-4ADA-A55C-5A2CD3158111](https://user-images.githubusercontent.com/60881723/169196271-897838ec-1958-497c-af8c-02dd03944ff6.png)
![985621BF-2FE1-4908-BD9B-2635AE411C75](https://user-images.githubusercontent.com/60881723/169196280-0058e546-2a40-4bb3-8bd9-5f08507bc258.png)
![856915E5-73E0-4666-8843-F0CF5BC8F136](https://user-images.githubusercontent.com/60881723/169196388-3eca8a9a-a083-4e2f-aa52-630e45774964.png)

**Comment by app2smile** [comment]
最近贴吧经常抽风, 建议搭配使用`广告联盟模块`.
贴吧的开屏广告有两种: 1种是贴吧自己的开屏广告 第二种是广告联盟的开屏广告

默认先加载贴吧自己的开屏, 但有时候就比较迷 会加载广告联盟的广告.

我再研究研究 临时解决办法就是卸载贴吧重新安装, 加载广告联盟模块 和贴吧去广告模块

**Comment by app2smile** [comment]
此问题已修复

保持模块加载的状态下,更新surge的外部资源文件.
然后打开贴吧,等待几秒后杀掉后台,重新打开贴吧即可

**Comment by Meonthb** [comment]
> 此问题已修复
> 
> 保持模块加载的状态下,更新surge的外部资源文件. 然后打开贴吧,等待几秒后杀掉后台,重新打开贴吧即可

现在好了，厉害了佬👍
