### ISSUE TITLE
Spotify quantumultx 不能解锁premium

### ISSUE THREAD

**Issue by 6324sunxiaochuan** [app2smile/rules#50]
有两个设备
qx版本1.0.28
ipad为ipados15.3 iphone为ios15.0.1 spotify版本8.7.22
ipad可以解锁premium
iphone不行
iphone上试过重装app 一开始现实的是vip 然后app加载了一下就不行了

**Comment by 6324sunxiaochuan** [comment]
人在国外 ip应该是稳定的

**Comment by 6324sunxiaochuan** [comment]
![b](https://user-images.githubusercontent.com/62925327/173610515-efa1a72a-9f9f-4777-a017-4f89fc0f0307.jpg)
![a](https://user-images.githubusercontent.com/62925327/173610531-e2d08cef-b867-4a7c-93c4-5baa78ce8715.jpg)
不知道大佬要的是不是这个 我没发现这个脚本print的相关日志
为了确保脚本触发，我又重装了一遍，一开始显示premium，点了搜索按钮后就没了

**Comment by app2smile** [comment]
抓下包 或者看最近请求 有没有https://spclient.wg.spotify.com/user-customization-service/v1/customize 这个链接的请求。看看是被拦截了，还是没有？ 如果没找到 看看有没有跟这个链接像的。

**Comment by 6324sunxiaochuan** [comment]
我iphone ipad的config不一样 iphone多了一些规则 是不是规则的precedence之类导致的？该怎么去排查这个问题呢？

**Comment by app2smile** [comment]
我对qx不是很了解，日常用Surge。看起来这个链接没有命中执行脚本

**Comment by 6324sunxiaochuan** [comment]
ipad的config拷贝过来就okay了
不是脚本本身的问题 可能是这个重写规则precedence有点低 导致被某个不明规则压了priority
非常大佬的及时回复 关issue了

**Comment by 6324sunxiaochuan** [comment]
不好意思大佬 我发现上次可以用只是因为iphone用了ipad的spotify设备共享，现在仍不行。。。

**Comment by app2smile** [comment]
应该是规则的问题,得让https://spclient.wg.spotify.com/user-customization-service/v1/customize 这个链接命中执行脚本才可以

**Comment by 6324sunxiaochuan** [comment]
现在又莫名其妙的好了 太感谢了
