### ISSUE TITLE
弹出pre解锁提示

### ISSUE THREAD

**Issue by dycwuxing** [app2smile/rules#51]
大佬，请问在搜索界面点击歌曲，就会弹出提示，需要升级pre，请问是什么原因导致的啊
![355AEC6A-CD01-46B1-A8A2-E8F97B435BE2](https://user-images.githubusercontent.com/44988562/176632123-61c58f86-ad3e-4362-84a6-5ce1585a18c1.png)
![41673160-01C7-4C95-9374-65B748724E8F](https://user-images.githubusercontent.com/44988562/176632144-7ef35c72-6caa-48d7-98a3-34665f1db5ec.png)
![63B5FBCD-BAA7-4C2D-9D6F-4D8D1BE52E7F](https://user-images.githubusercontent.com/44988562/176632155-4f12db4e-9ec8-4e45-997c-994145a5f5f0.png)
![Uploading E6BDC2BF-02AC-46EC-825B-0C457BC471DA.jpeg…]()

**Comment by dycwuxing** [comment]
音质设置的是 标准

**Comment by app2smile** [comment]
telegram帐号多少 看一下

**Comment by dycwuxing** [comment]
dycwuxing

**Comment by dycwuxing** [comment]
大佬你看看能不能私聊我,我私不了你.......
