### ISSUE TITLE
大佬，百度贴吧的去广告失效了

### ISSUE THREAD

**Issue by leowolf1993** [app2smile/rules#53]
目前不论是贴间还是贴内都有广告
点击进贴内有大概率程序卡死
请求更新，十分感谢！

**Comment by app2smile** [comment]
贴出贴吧版本 用的是surge还是loon qx呢？

模块 规则 js脚本都保持更新到最新。

如果还是不起效，抓下包 看看180.76.76.200这个有没有屏蔽

**Comment by app2smile** [comment]
把你的贴吧规则也截图让我看看

**Comment by leowolf1993** [comment]
贴吧版本是最新的12.25.1
使用的软件是qx
![9269A024-B981-42CD-A77C-B274E60482A0](https://user-images.githubusercontent.com/98311796/176798397-a5bcbd23-ea3e-4d62-aa21-a6cded45c51f.png)
![D9860F78-DFD9-49BB-97AF-C5A95E78775E](https://user-images.githubusercontent.com/98311796/176798404-9018d385-2500-4630-9226-d34b2627e134.png)

**Comment by app2smile** [comment]
进ui界面，
分流-引用 更新更新；
进重写-引用 和 重写-浏览 分别更新更新。确保是最新的规则和脚本

**Comment by leowolf1993** [comment]
> 进ui界面，
> 分流-引用 更新更新；
> 进重写-引用 和 重写-浏览 分别更新更新。确保是最新的规则和脚本

已经按照大佬的指示操作，但是依旧会有广告
![2EE562EE-C0CF-4297-A909-DDF4B419038C](https://user-images.githubusercontent.com/98311796/176798979-f765cd5f-5879-4ee7-aec5-3582546fd274.png)
![2F02AC38-E9FE-4DD5-B487-EF253D1627EB](https://user-images.githubusercontent.com/98311796/176798988-9e572f5e-3f93-40de-837f-57e1a2d0cf70.png)

**Comment by app2smile** [comment]
tg多少 一会帮你看看

**Comment by leowolf1993** [comment]
> tg多少 一会帮你看看

谢谢大佬
12249930727

**Comment by app2smile** [comment]
搜不到...

**Comment by leowolf1993** [comment]
> 搜不到...

大佬说一下你的吧 我加你～

**Comment by app2smile** [comment]
app2smile

**Comment by app2smile** [comment]
问题已解决, qx引用不同规则冲突导致
