### ISSUE TITLE
B站去广告模块报错

### ISSUE THREAD

**Issue by Zeaphyou** [app2smile/rules#54]
![image](https://user-images.githubusercontent.com/76173678/177065415-2e8b37a8-76ef-48dc-8a91-ee606bfb8732.png)

麻烦大佬看下是什么原因

**Comment by app2smile** [comment]
看起来是没响应信息.
刚做了下处理,你更新一下外部js文件

**Comment by Zeaphyou** [comment]
> 看起来是没响应信息.
> 
> 刚做了下处理,你更新一下外部js文件

更新后不再报错，但是现在还有个新问题，就是我用了那个解锁大会员画质的脚本，和这个模块一起用的时候，我的页面那里，上半部份加载不出来。🫠

**Comment by app2smile** [comment]
截图看看

**Comment by Zeaphyou** [comment]
> 截图看看

![image](https://user-images.githubusercontent.com/76173678/177067910-cf4db038-d2c1-4d60-8bd9-e23d38835c96.png)


![image](https://user-images.githubusercontent.com/76173678/177067922-d6e9b56b-6b3e-431c-9b2f-c7e436a2f43e.png)


看起来似乎是BiHD这个脚本的问题，但是我试用过另外一个去广告模块，这里不会有这个问题，只是他的模块在视频页面会出现UP主推荐广告。

**Comment by app2smile** [comment]
BiHD分享一下给我,

**Comment by app2smile** [comment]
视频页面和动态的广告目前只能用二进制脚本去除,其他的b站去广告大都是json格式的,去不了.

**Comment by Zeaphyou** [comment]
> BiHD分享一下给我,

/*
bilibili fan drama open 1080P+

From https://github.com/Sunert/Scripts/blob/master/Script/Bilibili/BiliHD.js

QX:
https:\/\/ap(p|i)\.bilibili\.com\/((pgc\/player\/api\/playurl)|(x\/v2\/account\/myinfo\?)|(x\/v2\/account/mine\?)) url script-response-body BiliHD.js

QX MITM = api.bilibili.com
*/

var body = $response.body;
var url = $request.url;

const path1 = '/pgc/player/api/playurl';
const path2 = "/x/v2/account/myinfo?";
const path3 = "/x/v2/account/mine\?";
if (url.indexOf(path1) != -1) {
    let obj = JSON.parse(body);   
    obj["has_paid"] = true;
	obj["quality"] = obj["accept_quality"][0];
	obj.vip_type = 2;
	obj.vip_status = 1;
 	body = JSON.stringify(obj);  
 };
if (url.indexOf(path2) != -1){
  let obj = JSON.parse(body);
    obj["data"]["vip"]["type"] = 2;
    obj["data"]["vip"]["status"] = 1;
    obj["data"]["vip"]["vip_pay_type"] = 1;
    obj["data"]["vip"]["due_date"] = 1669824160;

   body=JSON.stringify(obj);
 };
   
if (url.indexOf(path3) != -1){
  let obj = JSON.parse(body);
     obj["data"]["vip_type"] = 2;
     obj["data"]["vip"]["type"] = 2;
     obj["data"]["vip"]["status"] = 1;
     obj["data"]["vip"]["vip_pay_type"] = 1;
     obj["data"]["vip"]["due_date"] = 1669824160;
   body=JSON.stringify(obj);
};
   
 $done({body});

**Comment by app2smile** [comment]
测试了一下 这个解锁画质的没用,自我欺骗自己.
具体画质的流是服务器返回的,不是会员的话,有的视频最多给你返回1080的流,不会返回60帧和4K的流

**Comment by app2smile** [comment]
![image](https://user-images.githubusercontent.com/34903735/177071857-a13c039b-2592-468c-8dbd-e1ecc9b6ecf0.png)

**Comment by Zeaphyou** [comment]
> ![image](https://user-images.githubusercontent.com/34903735/177071857-a13c039b-2592-468c-8dbd-e1ecc9b6ecf0.png)
> 
> 
🫠😂了解了，多谢多谢
