### ISSUE TITLE
哔哩哔哩规则问题

### ISSUE THREAD

**Issue by RuCu6** [app2smile/rules#56]
grpc.biliapi.net

这个域名屏蔽以后会出现收不到私信的问题
右上角那个消息盒子

**Comment by app2smile** [comment]
去视频播放页和动态广告需要屏蔽这个域名,否则无法去除

**Comment by app2smile** [comment]
能否消息描述一下私信问题,我这测试了一下,加载脚本的时候是可以正常收到私信

**Comment by RuCu6** [comment]
我是混合使用的  用了bm7的重写和你的重写  添加了这个规则以后 私信进去是空白界面  删除规则后正常  目前也没发现什么广告

**Comment by app2smile** [comment]
不建议混用，很可能会冲突。

删掉规则还能去广告有可能你用的是http1.1

surge正式版http2下需要屏蔽这个域名 
最新surge tf版本不需要，但是需要对其进行mitm以及修改正则进行匹配。

**Comment by RuCu6** [comment]
好的好的  感谢热心回复
