### ISSUE TITLE
关于哔哩哔哩去广告的一个建议

### ISSUE THREAD

**Issue by RuCu6** [app2smile/rules#57]
佬 用你的重写以后 底部动态tab点进去 综合部分去掉了最常访问和推广  但是视频这部分顶部有最常访问和推广  如下图
![0F353001-A55A-4FE3-9E7D-BF4FF5179E85](https://user-images.githubusercontent.com/49463634/178885999-9c893f45-335b-42be-8287-43d2b59d18bb.png)
![562F9A5C-58F1-4AC0-AF32-5FAFA66D0987](https://user-images.githubusercontent.com/49463634/178886029-b73c1b34-6eaa-4e7a-8fd5-b4aa8ff99d42.jpeg)

底部我的tab可以做到下图这样吗 只保留红框部分的内容  这样更纯净
![8DEA0DEE-13EB-494C-804E-4F34AA52DB2C](https://user-images.githubusercontent.com/49463634/178886403-ab296440-047c-444f-b0a0-4fc426519465.jpeg)

非常感谢

**Comment by lzy4ever** [comment]
想精简我的页面可以下载非国区哔哩哔哩（白色图标），非常干净整洁
