### ISSUE TITLE
Spotify歌词翻译能否插入换行呢

### ISSUE THREAD

**Issue by hhx2018** [app2smile/rules#59]
开发者哥哥您好：
使用了您的Spotify歌词翻译插件后感觉很好，唯一的缺憾便是，翻译的结果（翻译结果），可否在其前面插入换行使得翻译的内容换行显示呢，读了一遍您的代码后，我太笨拙以至于找不到修改之处。
期待您的回复！

**Comment by app2smile** [comment]
换行试了下 比较丑，样式都变了。
另外百度翻译api8月份要升级了，建议开通高级版，标准版基本用不了了

**Comment by app2smile** [comment]
嗯 不超过就是免费

**Comment by hhx2018** [comment]
> 换行试了下 比较丑，样式都变了。 另外百度翻译api8月份要升级了，建议开通高级版，标准版基本用不了了

呜，我找到那一行代码了，确实加了换行后，翻译行和原歌词之间会莫名其妙多出来一个空行，的确比较丑唉！
无法理解 我只是加了一个\n，为什么会多出来一个空白行，好奇怪哟！

**Comment by tigerchen824** [comment]
开发者哥哥你好，这个歌词翻译怎么编辑输入那个id，我有点不会，请教一下你

**Comment by app2smile** [comment]
> 开发者哥哥你好，这个歌词翻译怎么编辑输入那个id，我有点不会，请教一下你

qx的话把脚本文件复制一份到自己的本地文件中（看qx配置中本地文件存放路径是在iCloud中还是iPhone本地）。然后找到脚本里面的说明填写一下appid和密钥，进行配置。

**Comment by tigerchen824** [comment]
老哥，成了，非常感谢

**Comment by donglee988** [comment]
博主能手把手教一下不？我不懂怎么复制到本地文件，以及复制什么内容> > 开发者哥哥你好，这个歌词翻译怎么编辑输入那个id，我有点不会，请教一下你
> 
> qx的话把脚本文件复制一份到自己的本地文件中（看qx配置中本地文件存放路径是在iCloud中还是iPhone本地）。然后找到脚本里面的说明填写一下appid和密钥，进行配置。

**Comment by fangbufan** [comment]
开发者先生，您好！咨询下您，我用您提供的脚本保存到Quantumult X的本地文件后，进行填写百度翻译的appid以及密钥并且重写 mttm域名也添加了，但是出现Spotify不翻译，大部分时候歌词页面显示白码，极少数刷新出歌词也是没翻译的情况，禁用此条重写，又全部恢复正常，Quantumult X也没任何报错弹窗，您在测试过程有遇到这种情况吗？
