### ISSUE TITLE
Spotify [Surge]

### ISSUE THREAD

**Issue by stonejihub** [app2smile/rules#61]
开发者你好，感谢你的脚本！

我有一个小白问题，这个Spotify解锁脚本（Surge）需要打开MitM吗？我不开MitM，我不确定解锁脚本是否成功运行了（有的时候连续播放很长时间也没Spotify广告）。我打开MitM以后，歌曲都无法播放。PS 我重新登录过，quality选择automatic

**Comment by app2smile** [comment]
1.需要开启mitm
2.你开启mitm后无法播放歌曲，建议你开启surge抓包，然后把抓包的结果截图发来定位你的问题。一般是自己surge配置导致的问题。
3.脚本需要iOS15系统
4.如果脚本正常加载运行，那么surge-工具-日志里面会有脚本运行日志。

**Comment by stonejihub** [comment]
非常感谢您的耐心回答和开发。我打开MitM，并且trust证书以后，好像能够随意切歌（没有广告）。我之前是失败的原因是没开MitM和打开MitM后没有信任证书。非常抱歉小白问题耽误你时间了。（另外问一下，M1 arm mac的surge支持这个Spotify脚本吗？
