### ISSUE TITLE
圈X spotify非中文歌词翻译脚本

### ISSUE THREAD

**Issue by maliouu** [app2smile/rules#63]
https://raw.githubusercontent.com/app2smile/rules/master/js/spotify-lyric.js 我把这个链接加进重写了，但是一直通知我翻译错误，请检查appid和密钥配置，看了链接没看懂在哪里添加，请作者详细说说（在哪里添加appid和密钥）。感谢

**Comment by app2smile** [comment]
用的是什么软件呢 surge还是啥

**Comment by maliouu** [comment]
圈X

**Comment by app2smile** [comment]
https://github.com/app2smile/rules/issues/59#issuecomment-1193064960

**Comment by app2smile** [comment]
qx不能直接引用这个脚本，按照上面说的 复制到本地 再做修改

**Comment by maliouu** [comment]
我把文复制到本地了但是还是用不了。

**Comment by maliouu** [comment]
可以发一下tg的联系方式吗 好发截图😭

**Comment by app2smile** [comment]
app2smile

**Comment by ooo888999** [comment]
怎么改id啊
