### ISSUE TITLE
大佬，surge用了bilibili模块，无法搜索了

### ISSUE THREAD

**Issue by Dor2m1** [app2smile/rules#64]
大佬，surge用了bilibili模块，无法搜索了

**Comment by app2smile** [comment]
模块没有对搜索进行拦截和修改。

可以通过抓包，看看是哪些规则发生了冲突 导致无法搜索。

**Comment by ddgksf2013** [comment]
> 模块没有对搜索进行拦截和修改。
> 
> 可以通过抓包，看看是哪些规则发生了冲突 导致无法搜索。

大佬，我qx用的您的重写，也无法搜索，B站为最新版；

通过我自行查找原因，是grpc.biliapi.net在搞事情，去掉该域名的mimt，B站即可正常搜索，但是导致的后果是无法正常屏蔽广告

您可以测试看下，针对无法搜索，有没有解决方法

**Comment by app2smile** [comment]
> 

我这边测试了一下无法重现... 是可以搜索的
我没加载其他冲突规则

b站会走两个域名 一个是grpc.biliapi.net  一个是app.bilibili.com 优先走的是grpc.biliapi.net

对于surge,如果开启了MITM HTTP2, 那么会走grpc.biliapi.net, 如果没开启h2,则会回退到app.bilibili.com

对于LOON和QX, 规则上都对grpc.biliapi.net进行了屏蔽,并且也MITM了(MITM之后屏蔽不屏蔽都可以, 因为LOON和QX无法对grpc.biliapi.net这个域名进行MITM,会自动回退到app.bilibili.com)

qx你可以尝试一下,看看https://raw.githubusercontent.com/app2smile/rules/master/rule/bilibili-ad-qx.list这个分流是否加载了(其实加载不加载无所谓,都不应该走grpc.biliapi.net)

对于loon和qx 只要抓包发现grpc.biliapi.net正常运行而不是屏蔽状态,那就是有问题的.

**Comment by app2smile** [comment]
> 

个人猜测 应该还是不同规则间叠加冲突导致

**Comment by ddgksf2013** [comment]
> 个人猜测 应该还是不同规则间叠加冲突导致

我再细细查找一下，谢谢大佬答复

**Comment by app2smile** [comment]
> > 个人猜测 应该还是不同规则间叠加冲突导致
> 
> 我再细细查找一下，谢谢大佬答复

看了你的仓库,b站规则挺多,有一些是无效的:
1.动态的老域名现在应该是无效了.b站现在走的是二进制数据,之前的老规则不需要
2.1080P4K解锁的属于客户端自我欺骗, 真实服务器返回的数据仍然是达不到60帧和4K的. 服务器会根据个人是否是会员返回不同的视频流

**Comment by ddgksf2013** [comment]
实际测试如下

B站V6.86.0，QX TF V749重写列表只开启一个：

https://raw.githubusercontent.com/app2smile/rules/master/module/bilibili-qx.conf

打开B站无法搜索（未屏蔽grpc.biliapi.net）

屏蔽grpc.biliapi.net，添加-grpc.biliapi.net，无法搜索

不屏蔽grpc.biliapi.net，添加-grpc.biliapi.net，可以搜索

**Comment by app2smile** [comment]
> 实际测试如下
> 
> B站V6.86.0，QX TF V749重写列表只开启一个：
> 
> https://raw.githubusercontent.com/app2smile/rules/master/module/bilibili-qx.conf
> 
> 打开B站无法搜索（未屏蔽grpc.biliapi.net）
> 
> 屏蔽grpc.biliapi.net，添加-grpc.biliapi.net，无法搜索
> 
> 不屏蔽grpc.biliapi.net，添加-grpc.biliapi.net，可以搜索

等qx出正式版我再看看, 我这没TF,用的1.0.31.746正式版测试的

**Comment by yanhaoch** [comment]
圈x使用https://raw.githubusercontent.com/app2smile/rules/master/module/bilibili-qx.conf重写
无法搜索
最新版bilibili 和圈x

**Comment by ddgksf2013** [comment]
下午，我退回qx商店最新版，也还是无法搜索，不mimt这个grpc.biliapi.net，立马可以搜索，晚上试试降级B站

**Comment by app2smile** [comment]
我这俩手机都无法还原该问题.

surge loon qx b站搜索,动态去广告都正常,暂不清楚问题

**Comment by ddgksf2013** [comment]
经过几番折腾，确定为B站APP本身问题（引用规则不变，逐一降级Bilibili）

当B站降级至V6.85.0时，搜索立即可用（ID：851409639）

对比V6.85.0与V6.86.0搜索时的域名，发现85版的是

https://app.bilibili.com/x/v2/search?access

而86版的是

https://app.bilibili.com/bilibili.polymer.app.search.v1.Search/SearchAll

**Comment by app2smile** [comment]
我的b站版本为6.87

搜索请求的路径为https://app.bilibili.com/x/v2/search

有可能是根据不同用户做了abtest

**Comment by 0309zuochen** [comment]
所以b站的会员无法通过代理软件解锁吗

**Comment by app2smile** [comment]
个人始终无法复现该问题
