### ISSUE TITLE
spotify 重新失败

### ISSUE THREAD

**Issue by LXY631** [app2smile/rules#65]
ios 版本15.5，spotify版本8.7.40.1558，quanx 2022.08.26更新版本，目前无法重写成功

**Comment by app2smile** [comment]
无法重现，一般是规则冲突或者配置问题。

可抓包搜索重写的url，通过查看url以及脚本日志，确定原因。

如果脚本正常执行（日志中有脚本的输出），仍然无法播放，先确认自己的账号能否在pc端播放。

**Comment by InnocenseYu** [comment]
> 

谢谢回复，太打扰了。软件被小朋友乱按关闭了重新功能，之前一直记得是没有更新spotify和之前正常使用的。
