### ISSUE TITLE
哔哩哔哩开屏广告屏蔽似乎失效了

### ISSUE THREAD

**Issue by NekoShizuku** [app2smile/rules#67]
最近两天，我打开哔哩哔哩出现了开屏广告，其他都完美屏蔽了，可能是B站新广告服务器吗？我尝试更新了规则，还是没成功

**Comment by app2smile** [comment]
可以抓包请求，查看开屏链接命中了什么规则，或者命中了什么脚本。

本模块是通过js修改的，没有设置拦截规则。

如果确定是命中了本模块的脚本，可以把详细链接截图发来帮助研究

**Comment by NekoShizuku** [comment]
没事了，我把grpc.biliapi.net给Reject了，开屏广告就无了
