### ISSUE TITLE
Surge贴吧去广告无法去除开屏广告

### ISSUE THREAD

**Issue by MeoCag** [app2smile/rules#7]
其他广告都可以去除，唯独开屏广告依旧存在

IOS版本：15.0.2 (19A404)
Surge版本：4.9.3

**Comment by app2smile** [comment]
出现这种情况一般是自己的原因，按照以下步骤排除：
1.确认mitm开启
2.确认没有其他规则冲突
3.确认手机网络正常（网络信号差的时候会有开屏广告）
4.wifi切蜂窝的时候surge会漏请求
5.贴出你的日志运行情况

**Comment by app2smile** [comment]
这个日志看不出什么，需要看脚本的执行日志。脚本如果成功执行会输出开屏页的日志。

**Comment by Meonthb** [comment]
是直接在脚本编辑器里选择导入脚本后运行吗？如果是的话，运行结果如下：

运行贴吧proto：
![贴吧proto](https://i.imgur.com/ruvkFsO.jpg)
运行贴吧json:
![贴吧proto](https://i.imgur.com/MTyMZix.jpg)

**Comment by app2smile** [comment]
从你的日志上看，没有被mitm

**Comment by Meonthb** [comment]
谢谢帮助，重启mitm后就正常工作了，原理未知

----------------------------
21:44:56.108497 贴吧-开屏页
21:44:56.109374 成功
21:44:56.110766 [Script Completed]
----------------------------
