### ISSUE TITLE
哔哩哔哩qx重写规则能否自定义取消部分功能

### ISSUE THREAD

**Issue by lzy4ever** [app2smile/rules#71]
大佬你好，请问一下如果想要保留哔哩哔哩动态的最常访问只屏蔽其他广告的话，应该怎么操作一下？谢谢，麻烦了

**Comment by app2smile** [comment]
暂不支持,如果需要的话可以自己把脚本js文件复制一份到本地,进行修改和配置,js里面有最常访问的代码,删掉.

不过脚本更新的时候,需要自己手动定期更新.
