### ISSUE TITLE
Quantumult X bilibili开屏去广告以及移除动态话题和最近访问会偶然性失效

### ISSUE THREAD

**Issue by aico267** [app2smile/rules#72]
bilibili开屏去广告、动态相关去除再我添加了您的规则后仍然会偶然性失效。而一些标签页简化则一切安好。

**Comment by app2smile** [comment]
失效的时候，打开surge抓包，再刷新动态等，观察一下接口命中了什么脚本。

有了请求和抓包记录，才能方便排查你的情况是什么原因。

**Comment by aico267** [comment]
好的！最近没怎么遇到过这个问题了。可能是我网络不太好，等我遇到了这个问题会抓包提供信息方便您排查情况。感谢您的回答。> 失效的时候，打开surge抓包，再刷新动态等，观察一下接口命中了什么脚本。
> 
> 有了请求和抓包记录，才能方便排查你的情况是什么原因。
>
