### ISSUE TITLE
新版贴吧去广告会导致贴吧无法刷新内容

### ISSUE THREAD

**Issue by baixiongnull** [app2smile/rules#73]
之前的贴吧，用去广告会导致刷帖非常卡顿，进一个帖子要卡很久，现在更新后则刷新不了了。

**Comment by app2smile** [comment]
贴吧最新版本修改了接口，已初步做过适配。
你需要重新更新一下贴吧去广告模块和js脚本

**Comment by app2smile** [comment]
loon 和qx也已适配

**Comment by vwoodyv** [comment]
适配了？

**Comment by app2smile** [comment]
适配过了 有问题及时反馈

**Comment by baibai0222** [comment]
有没有小火箭的

**Comment by app2smile** [comment]
小火箭不清楚, 你可以尝试一下. 
因为新版贴吧走json接口了, 不排除还会变为protobuf格式.

**Comment by app2smile** [comment]
贴吧已恢复protobuf
