### ISSUE TITLE
Spotify歌词翻译请求添加腾讯云机器翻译接口

### ISSUE THREAD

**Issue by lfz-5** [app2smile/rules#74]
腾讯云[机器翻译](https://cloud.tencent.com/document/product/551/35017) 接口每月五百万字符免费额度，按量付费，超出部分付费。好像也不错，如果您觉得可以，麻烦您有空添加，感谢！
![431129E8-C68B-45FC-B527-12CE0C50CBFE](https://user-images.githubusercontent.com/43802521/195868049-5872f96d-426c-48d0-8d6e-06e3d50a42bb.png)

**Comment by app2smile** [comment]
抱歉，个人精力有限，暂不支持
