### ISSUE TITLE
Spotify现在小火箭可以使用吗？为啥之前还可以用现在不行了🥹

### ISSUE THREAD

**Issue by baibai0222** [app2smile/rules#75]

**Comment by xzy0601** [comment]
最近确实失效了

**Comment by app2smile** [comment]
没有小火箭，也没有针对小火箭做测试

**Comment by xzy0601** [comment]
用的quantumult x 上周失效的

**Comment by app2smile** [comment]
可以查看日志看看脚本是否执行了

**Comment by a1564471347** [comment]
> 可以查看日志看看脚本是否执行了

已经失效了，专辑里面的歌曲只显示名字了不能选歌了
![A72DFB99-F7F4-48A3-BF71-AE79098D22D2](https://user-images.githubusercontent.com/65760851/197335486-e0a9529f-b434-404e-aae0-1efe31e7a967.png)
![430E8927-022E-466F-B107-BA91780FCF6D](https://user-images.githubusercontent.com/65760851/197335491-2caa3c0d-6b13-4ddf-8bf5-2ff1d5b4feb3.jpeg)

**Comment by app2smile** [comment]
> > 可以查看日志看看脚本是否执行了
> 
> 
> 
> 已经失效了，专辑里面的歌曲只显示名字了不能选歌了
> 
> ![A72DFB99-F7F4-48A3-BF71-AE79098D22D2](https://user-images.githubusercontent.com/65760851/197335486-e0a9529f-b434-404e-aae0-1efe31e7a967.png)
> 
> ![430E8927-022E-466F-B107-BA91780FCF6D](https://user-images.githubusercontent.com/65760851/197335491-2caa3c0d-6b13-4ddf-8bf5-2ff1d5b4feb3.jpeg)
> 
> 

一直都不支持专辑歌曲啊。。。

**Comment by a1564471347** [comment]
> 

我前几天还可以专辑选歌

**Comment by app2smile** [comment]
这个功能脚本一直都不支持，专辑选歌是会员功能

**Comment by a1564471347** [comment]
> 

昨天之前我都可以，就用的你这脚本，今天突然不能选了
