### ISSUE TITLE
Spotify 总是提示id 和密码错误，有没有id 填写的方式

### ISSUE THREAD

**Issue by Solomeyou** [app2smile/rules#77]

**Comment by app2smile** [comment]
具体点 是哪个脚本？还是说你说的是spotofy登陆提示？

**Comment by Solomeyou** [comment]
翻译脚本

获取 Outlook for iOS<https://aka.ms/o0ukef>
________________________________
发件人: app2smile ***@***.***>
发送时间: Thursday, October 27, 2022 11:18:20 AM
收件人: app2smile/rules ***@***.***>
抄送: Solomeyou ***@***.***>; Author ***@***.***>
主题: Re: [app2smile/rules] Spotify 总是提示id 和密码错误，有没有id 填写的方式 (Issue #77)


具体点 是哪个脚本？还是说你说的是spotofy登陆提示？

―

**Comment by Solomeyou** [comment]
这个样子

获取 Outlook for iOS<https://aka.ms/o0ukef>
________________________________
发件人: 韩 西瑞 ***@***.***>
发送时间: Thursday, October 27, 2022 11:19:39 AM
收件人: app2smile/rules ***@***.***>; app2smile/rules ***@***.***>
抄送: Author ***@***.***>
主题: Re: [app2smile/rules] Spotify 总是提示id 和密码错误，有没有id 填写的方式 (Issue #77)

翻译脚本

获取 Outlook for iOS<https://aka.ms/o0ukef>
________________________________
发件人: app2smile ***@***.***>
发送时间: Thursday, October 27, 2022 11:18:20 AM
收件人: app2smile/rules ***@***.***>
抄送: Solomeyou ***@***.***>; Author ***@***.***>
主题: Re: [app2smile/rules] Spotify 总是提示id 和密码错误，有没有id 填写的方式 (Issue #77)


具体点 是哪个脚本？还是说你说的是spotofy登陆提示？

―

**Comment by app2smile** [comment]
具体使用方式已经写在脚本中了。点开脚本就可以查看

**Comment by Solomeyou** [comment]
主机和复写都已经添加过了，账号密码是输入在
  ‘ ’中间么，还是怎样，愁死我了

获取 Outlook for iOS<https://aka.ms/o0ukef>
________________________________
发件人: app2smile ***@***.***>
发送时间: Thursday, October 27, 2022 11:22:00 AM
收件人: app2smile/rules ***@***.***>
抄送: Solomeyou ***@***.***>; Author ***@***.***>
主题: Re: [app2smile/rules] Spotify 总是提示id 和密码错误，有没有id 填写的方式 (Issue #77)


具体使用方式已经写在脚本中了。点开脚本就可以查看

―

**Comment by app2smile** [comment]
qx要输入的是百度翻译的appid和密钥

**Comment by Solomeyou** [comment]
是这个，还是自己的百度账号

获取 Outlook for iOS<https://aka.ms/o0ukef>
________________________________
发件人: app2smile ***@***.***>
发送时间: Thursday, October 27, 2022 11:28:12 AM
收件人: app2smile/rules ***@***.***>
抄送: Solomeyou ***@***.***>; Author ***@***.***>
主题: Re: [app2smile/rules] Spotify 总是提示id 和密码错误，有没有id 填写的方式 (Issue #77)


qx要输入的是百度翻译的appid和密钥

―

**Comment by Solomeyou** [comment]
我那个账号密码，就是直接复制的这个id 和密匙，Qx就一直提示密码错误，主要是想确认下，这样配置是否ok ，然后密码和id 填写方式是否正确

获取 Outlook for iOS<https://aka.ms/o0ukef>
________________________________
发件人: 韩 西瑞 ***@***.***>
发送时间: Thursday, October 27, 2022 11:36:17 AM
收件人: app2smile/rules ***@***.***>; app2smile/rules ***@***.***>
抄送: Author ***@***.***>
主题: Re: [app2smile/rules] Spotify 总是提示id 和密码错误，有没有id 填写的方式 (Issue #77)

是这个，还是自己的百度账号

获取 Outlook for iOS<https://aka.ms/o0ukef>
________________________________
发件人: app2smile ***@***.***>
发送时间: Thursday, October 27, 2022 11:28:12 AM
收件人: app2smile/rules ***@***.***>
抄送: Solomeyou ***@***.***>; Author ***@***.***>
主题: Re: [app2smile/rules] Spotify 总是提示id 和密码错误，有没有id 填写的方式 (Issue #77)


qx要输入的是百度翻译的appid和密钥

―

**Comment by Solomeyou** [comment]
我搞定了，大佬，我以为要在复写里边操作，没想到是task 没注意审题，打扰了大佬，祝大佬路上捡钱🐃

获取 Outlook for iOS<https://aka.ms/o0ukef>
________________________________
发件人: 韩 西瑞 ***@***.***>
发送时间: Thursday, October 27, 2022 11:53:12 AM
收件人: app2smile/rules ***@***.***>; app2smile/rules ***@***.***>
抄送: Author ***@***.***>
主题: Re: [app2smile/rules] Spotify 总是提示id 和密码错误，有没有id 填写的方式 (Issue #77)

我那个账号密码，就是直接复制的这个id 和密匙，Qx就一直提示密码错误，主要是想确认下，这样配置是否ok ，然后密码和id 填写方式是否正确

获取 Outlook for iOS<https://aka.ms/o0ukef>
________________________________
发件人: 韩 西瑞 ***@***.***>
发送时间: Thursday, October 27, 2022 11:36:17 AM
收件人: app2smile/rules ***@***.***>; app2smile/rules ***@***.***>
抄送: Author ***@***.***>
主题: Re: [app2smile/rules] Spotify 总是提示id 和密码错误，有没有id 填写的方式 (Issue #77)

是这个，还是自己的百度账号

获取 Outlook for iOS<https://aka.ms/o0ukef>
________________________________
发件人: app2smile ***@***.***>
发送时间: Thursday, October 27, 2022 11:28:12 AM
收件人: app2smile/rules ***@***.***>
抄送: Solomeyou ***@***.***>; Author ***@***.***>
主题: Re: [app2smile/rules] Spotify 总是提示id 和密码错误，有没有id 填写的方式 (Issue #77)


qx要输入的是百度翻译的appid和密钥

**Comment by WooyJen** [comment]
@Solomeyou 老哥 圈叉的Spotify翻译 咋配置呀 目前我是把https://raw.githubusercontent.com/app2smile/rules/master/js/spotify-lyric.js这个链接放到了重写引用里 然后按照配置说明添加了一条重写规则，就是const options = {
    appid: '',
    securityKey: ''
};这个ID和秘钥是配置在哪里呢
