### ISSUE TITLE
Spotify歌词js部份歌曲不起作用

### ISSUE THREAD

**Issue by MatrixLau** [app2smile/rules#78]
比如LadyGaga的Stupid Love和Taylor Swift的Lavender Haze没有触发到js，具体原因不知道为啥

<sub>Sent from <a href="https://apps.apple.com/cn/app/id1314212521">PPHub</a></sub>

**Comment by app2smile** [comment]
有没有触发可以查看日志。
我这测试目前正常。

你看看日志如何展示的

**Comment by MatrixLau** [comment]
> 有没有触发可以查看日志。 我这测试目前正常。
> 
> 你看看日志如何展示的

如图是上一首播了韩文歌 然后现在播了Lavender Haze日志没更新的
![70F4BA55-6F6C-4546-8A6A-6BA8F39FA0BB](https://user-images.githubusercontent.com/41422920/198812668-250ed069-f238-431c-a862-045cefd523e9.png)
一开始我怀疑是歌词本地存储了之类的 我就去清了一下软件的快存储 发现没用 不知道为啥 就别的歌进去歌词都会需要加载一下 但是我指出的那几首就不用加载 那可能是软件的问题

**Comment by app2smile** [comment]
本地是会有缓存的。

**Comment by MatrixLau** [comment]
> 本地是会有缓存的。

好的吧 确实我刚刚pad可以用翻译 这几首歌
