### ISSUE TITLE
Spotify 歌单歌曲下载功能异常

### ISSUE THREAD

**Issue by microka** [app2smile/rules#80]
iOS 16.1.1
Surge 5.20.0 (2573)
Spotify 8.7.82.107
点击歌单的下载按钮，按钮开始转圈圈，但实际并没有对歌单中的歌曲进行下载缓存，只有点击某首歌曲开始播放后才会对那首歌开始下载缓存，且无法分辨出哪些歌曲是实际已下载缓存至本地的。
请问上面的问题是否都无解？

**Comment by app2smile** [comment]
不支持下载
