### ISSUE TITLE
spotify 解锁跨区14天

### ISSUE THREAD

**Issue by LXY631** [app2smile/rules#82]
spotify 脚本可以解锁跨区14天限制吗，因为PC端和ios端的IP地区不同，但是又想用一个账号

**Comment by app2smile** [comment]
不可以

**Comment by LXY631** [comment]
> 不可以

明白了，谢谢您，开发者。

目前哪个最新版本可以成功解锁 Spotify 呢，看到8.7.18版本不可以唱歌，但是8.7.40就可以，平时怕更新后解锁失败就不该更新了

**Comment by app2smile** [comment]
保持最新版本就行 无需特定版本

**Comment by LXY631** [comment]
> 保持最新版本就行 无需特定版本

好的，太感谢您了，目前 app store 的版本是8.7.82
