### ISSUE TITLE
YouTube 首页、播放页广告

### ISSUE THREAD

**Issue by InnocenseYu** [app2smile/rules#83]
YouTube qx重写脚本去首页瀑布流广告不彻底，实际中仍然很多；播放页推荐列表也是；

日志中有脚本运行，广告也有去除

![image](https://user-images.githubusercontent.com/103131176/202119393-5eefbca7-e4fa-422d-aaa8-fe7f07ecd035.png)

![image](https://user-images.githubusercontent.com/103131176/202118590-1b2156c4-1750-4667-ae87-86535e5ae974.png)

![image](https://user-images.githubusercontent.com/103131176/202118633-7e1ff3f8-30c4-4375-8cf9-a79caca757d6.png)

![image](https://user-images.githubusercontent.com/103131176/202118778-07451cc1-f111-4ea6-90ba-ca5ee6099dc6.png)

![image](https://user-images.githubusercontent.com/103131176/202118831-a956aaaa-80b8-459b-994f-6b7bdbce2fa5.png)

**Comment by app2smile** [comment]
播放页的失效了,暂时没管

首页的我一会添加一下.

**Comment by InnocenseYu** [comment]
> 播放页的失效了,暂时没管
> 
> 
> 
> 首页的我一会添加一下.

麻烦您了，辛苦～

**Comment by app2smile** [comment]
更新了首页的js文件, 你需要更新一下js 如果还有广告请告知

**Comment by InnocenseYu** [comment]
> 更新了首页的js文件, 你需要更新一下js 如果还有广告请告知

好的，我现在就试试，太麻了，谢谢开发者

**Comment by InnocenseYu** [comment]
> 更新了首页的js文件, 你需要更新一下js 如果还有广告请告知

首页完美移除广告，非常棒；

但是 搜索界面 展示的视频流仍然有广告。
