### ISSUE TITLE
12.32.1 版贴吧去广告失效（已解决/和其他规则冲突）

### ISSUE THREAD

**Issue by Tangfffyx** [app2smile/rules#84]
帖子详情页直播广告，楼间广告

**Comment by app2smile** [comment]
这边无法还原。请提供更详细的日志和抓包信息

**Comment by Tangfffyx** [comment]
“直播间”广告关了没有再出现，楼间 app 广告仍然有。
![69480950-CDDC-411D-8948-B7925C3DE88D](https://user-images.githubusercontent.com/115964760/202189334-027e42a0-f53c-46a7-bb7d-523a168571ff.jpeg)
![E7312F84-71D4-4914-ABEA-EAC6A54B9559](https://user-images.githubusercontent.com/115964760/202189345-87e07293-dde6-42a7-97cf-dfcb4c9f5364.jpeg)
![B1D412D8-1F45-4D87-AAF2-A2FE49715662](https://user-images.githubusercontent.com/115964760/202189351-f54e326f-cdbb-4c36-8d1e-1659759192d4.jpeg)
![DDE3992C-CBCC-496D-955C-F57D3A82A020](https://user-images.githubusercontent.com/115964760/202189355-8add114c-13c5-4fbe-a7fa-0480f41c5df8.png)

**Comment by app2smile** [comment]
盲猜你的其他规则跟贴吧规则冲突了。杀掉贴吧app，然后再打开贴吧，之后你在qx搜索一下最近的请求，搜索这俩：

c/s/sync
180.76.76.200

再看看你的脚本日志

最后把你加载我的贴吧规则截图过来

**Comment by Tangfffyx** [comment]
![41518A83-FE70-40CA-A61D-19BA77A4B01C](https://user-images.githubusercontent.com/115964760/202192597-411cc0de-d5a1-42d0-84a3-28f18c54ce9c.png)
![75FD620C-A0DE-4953-A333-119C166F8D7D](https://user-images.githubusercontent.com/115964760/202192607-36cc723c-8a54-4aab-97ab-d861c90908ae.png)
c/s/sync好像有直连成功，额

**Comment by app2smile** [comment]
能把sync截图给我看看吗？
还有翻翻脚本日志中有sync的吗？

**Comment by Tangfffyx** [comment]
分流 sync 那里看不出有什么其他规则接管，脚本里含 sync 的只有您的去广告
![F4B55002-43FC-4FA1-9B70-4AD82F57AE9A](https://user-images.githubusercontent.com/115964760/202194282-4ad39e52-a3e5-4b92-9ddc-d586beb84bbe.png)

![35BBB05C-DD32-4F1F-8FF7-D88B742B3A2E](https://user-images.githubusercontent.com/115964760/202194274-f72fc012-a3e1-465f-b126-575b7f668599.png)
![0BC60C86-19B3-4A8A-83F6-54796646FBD1](https://user-images.githubusercontent.com/115964760/202194261-800037a7-0018-486f-bfde-18d8f4f77dcf.jpeg)

**Comment by app2smile** [comment]
![image](https://user-images.githubusercontent.com/34903735/202194965-c425ac3b-ebf3-4475-8ee7-a078aeb26c8b.jpeg)

这不是冲突的规则吗？去掉它

**Comment by app2smile** [comment]
贴吧的规则 除了我的不要加载其他的，其他的规则都是无用规则。

**Comment by Tangfffyx** [comment]
谢谢大佬，搞定

**Comment by baixiongnull** [comment]
我也是这个情况，也是那个冲突了，但是我不知道怎么删掉它

![CD940907-C72A-4C0C-94B8-7A56322AD7E8](https://user-images.githubusercontent.com/112310352/204102363-692c982c-2dc5-4d4f-b6c0-c0df35a3802b.png)
![3BF83224-2EF9-4F25-93C3-A7B279691809](https://user-images.githubusercontent.com/112310352/204102367-277e1fc1-cbbe-43b2-a41a-7907105b0496.png)

**Comment by baixiongnull** [comment]
试了好多次，把神机的重写和分流禁用了就没问题了，看来神机规则真的老了没人维护了吗……
