### ISSUE TITLE
哔哩哔哩反馈

### ISSUE THREAD

**Issue by RuCu6** [app2smile/rules#86]
哔哩哔哩proto版本 2022.11.18
哔哩哔哩版本 7.7.0
qx版本 1.1.0 已屏蔽 grpc.biliapi.net

在播放横屏视频时大概率造成进度条回退
表现为在播放5s左右时 进度条会回到开头

关闭proto脚本，回退消失

**Comment by app2smile** [comment]
可以抓包进一步排查问题。

**Comment by app2smile** [comment]
这边无法复现，你先住抓包，通过观察脚本执行日志 和抓包请求 进一步排查问题所在

**Comment by vwoodyv** [comment]
哔哩哔哩重度使用者建议使用外区白色Bilibili
