### ISSUE TITLE
Spotify部分歌曲无法播放

### ISSUE THREAD

**Issue by kurtn2005** [app2smile/rules#87]
iPhone 13 Pro
iOS 16.1.1
Surge 5.2.0 (Build 2567)
Spotify 8.7.86.510

直接引用模块，已经重新登陆，重启手机，重启Surge，重启Spotify，音质设置为高。

现象少量歌曲无法播放，点击歌曲后会在下方弹出播放小窗口后迅速消失。Surge中模块日志未见异常。
15:36:59.004599 [Script Completed]
----------------------------
15:51:16.753039 customize
15:51:16.753455 29560---29560
15:51:16.753533 [Script Completed]
----------------------------
目前发现几首不能播放（使用的是Billboard Hot 100歌单）：
Unholy - Sam Smith
As It Was - Harry Styles
I'm Good(Blue) - David Guetta
Super Freaky Girl - Nicki Minaj

**Comment by app2smile** [comment]
检查一下你之前是不是听过这些歌曲。

歌曲有缓存，如果之前听的时候设置的是超高音质，之后没了会员，无论设置的音质是啥，都会加载之前的缓存，导致无法播放。

最快的解决办法是删除spotify，重新下载。
或者清除spotify的缓存

**Comment by kurtn2005** [comment]
> 检查一下你之前是不是听过这些歌曲。
> 
> 歌曲有缓存，如果之前听的时候设置的是超高音质，之后没了会员，无论设置的音质是啥，都会加载之前的缓存，导致无法播放。
> 
> 最快的解决办法是删除spotify，重新下载。 或者清除spotify的缓存

感谢指导，看来是这个问题，我重新安装了Spotify可以了。
