### ISSUE TITLE
大佬，贴吧模块又无法去除开屏广告了

### ISSUE THREAD

**Issue by Meonthb** [app2smile/rules#9]
这次贴吧模块能mitm afd.baidu.com，但还是无法拦截开屏广告
![](https://i.imgur.com/n1jPmYN.jpg)
![](https://i.imgur.com/UvB1bAw.jpg)

**Comment by lijing-love** [comment]
大神多弄点主流的app！

**Comment by app2smile** [comment]
> 大神多弄点主流的app！

不同的app规则维护比较麻烦,如果不是自用的app也没办法做到维护. 目前只支持个人使用到的app
