### ISSUE TITLE
spotify部分破解似乎失效了

### ISSUE THREAD

**Issue by chenjk6271** [app2smile/rules#91]
之前用您的Quantumult X脚本破解spotify premium，加载脚本后可以在专辑内自由选歌、听歌，而这几天突然不能自由选歌了，只能随机播放（免费版的操作），但是还是显示账号是premium状态。目前是最新8.7.88版本，抓包ipa退回到之前的spotify版本也没用，可能不是更新导致问题，是否是脚本失效了？

**Comment by app2smile** [comment]
说明你之前真的是会员。有的账号注册后可以试用会员
脚本不支持专辑和歌手页面选歌。

可以搜索播放加到播放列表播放。也可以播放歌单。

**Comment by 1nC0deWeTrust** [comment]
![image](https://user-images.githubusercontent.com/25895481/205492619-2bea482c-3da4-47bf-8cda-f896ed0e34c9.png)

现在确实有问题，只能听首页的推荐歌单了，之前底部tab是没有加入Premium图标的，现在有了。切歌还会弹上面的Premium提示。

**Comment by app2smile** [comment]
检查你的脚本是否运行，根据你的描述脚本没运行。另外被官方限制的账号也是没办法破解的。

**Comment by 1nC0deWeTrust** [comment]
![image](https://user-images.githubusercontent.com/25895481/205494560-fbbe90d9-c8d6-4513-ad46-f0ff8bb49aa3.png)

![image](https://user-images.githubusercontent.com/25895481/205494566-f7dc5d86-ae71-4526-9c90-30f4ff357976.png)

进入Spotify的时候App肯定没有请求这个接口。

**Comment by app2smile** [comment]
可以使用其他账号测试一下。 目前没有接收到其他有关失效的反馈。
大部分的原因都在于代理软件的配置或者账号上
