### ISSUE TITLE
spotify突然失效了

### ISSUE THREAD

**Issue by JPGC123** [app2smile/rules#92]
用着突然不行了，一些歌单可以随便选，一些不行，搜索歌手进入专辑没法选择

**Comment by JPGC123** [comment]
声破天版本8.7.90

**Comment by JPGC123** [comment]
![F4AD0DEC-A1DA-4791-B7F9-295B7C4E32CD](https://user-images.githubusercontent.com/49173433/206201600-88dd14bf-feee-4ae4-861f-f5ad772d4526.png)

**Comment by app2smile** [comment]
一直都不支持歌手和专辑的选歌。

之前能用只能说明你的帐号是会员。

**Comment by JPGC123** [comment]
ok，了解了😂，谢谢解答

**Comment by app2smile** [comment]
就用歌单或者搜索歌曲加红心播放吧。

**Comment by kurtn2005** [comment]
> 就用歌单或者搜索歌曲加红心播放吧。

老大，Amazon Music的Free版方便看看不？是不是也能按照这个思路搞一搞？
