### ISSUE TITLE
Spotify解锁不稳定

### ISSUE THREAD

**Issue by Nyako33** [app2smile/rules#93]
之前都很稳定 今天开始就变得有时候能用有时候不能用

**Comment by app2smile** [comment]
描述更详细一些 比如哪些功能不能用 不稳定是什么表现？
还需要附上版本 日志

**Comment by app2smile** [comment]
脚本没在小火箭上测试过，也不知道能否在小火箭运行

**Comment by Nyako33** [comment]
目前解决了 应该是我这边的配置问题😂
