### ISSUE TITLE
spotify 部分premium已失效

### ISSUE THREAD

**Issue by Serein1202** [app2smile/rules#94]
规则已失效，辛苦大佬有时间可以更新一下，目前系统为iOS16.3，spotify版本为8.7.90.459，目前相关功能已完全失效，无法随意切歌【一小时只能切6首，再切则会弹出试用premium选项】，菜单出现premium，广告目前暂未出现
![IMG_4952 PNG](https://user-images.githubusercontent.com/33860649/207803925-39332ce4-e126-4e1c-8eca-8a3727bf6b75.JPG)
![IMG_4950 PNG](https://user-images.githubusercontent.com/33860649/207803942-ac52a684-7f59-4d73-9f0d-804b0cf679b0.JPG)
![lQDPJwJAd64OncDNCtrNBQSwbTf_1H7mxmQDltAbEkBuAA_1284_2778](https://user-images.githubusercontent.com/33860649/207803955-ef7e68bd-029d-4153-b157-81af27d5c246.jpg)

**Comment by app2smile** [comment]
确认下脚本是否运行, 看看脚本日志. 刚自测没问题

**Comment by Crystal0504** [comment]
改了一下rewrite文件重新导入后重新登录一下就好了，谢谢大佬~
