### ISSUE TITLE
Spotify会员WiFi状态下用不了，蜂窝数据可用。

### ISSUE THREAD

**Issue by Hbbpp** [app2smile/rules#96]
用了分流规则也没有用，就是WiFi状态下用不了，恢复成非会员模式。蜂窝数据就可以破解成会员模式。这是为什么

**Comment by Hbbpp** [comment]
圈x的

**Comment by Hbbpp** [comment]
![Uploading 8238C8FD-6F9F-4702-892A-C333E747A5D4.png…]()

**Comment by Hbbpp** [comment]
![529E088C-0BCB-4ECA-AD83-36C25E3A51C0](https://user-images.githubusercontent.com/120747225/208229077-350b0a42-5344-4eac-b7b3-4e4118303fad.png)

**Comment by app2smile** [comment]
脚本报错了，具体是啥看不出来，因为通知没兼容qx。你可以抓包截图这个请求看看url

**Comment by Chilledwatermelon** [comment]
我也是，老哥解决了嘛
